# Image prompts for every picture the players see.
# Each entry: (file path inside public/, name, prompt). The shared STYLE is added to every prompt.
# The prompts avoid the names from the books and films, so image tools make original art.

STYLE = ('Painted storybook fantasy illustration, gothic magical boarding school, rich candlelit colours '
         '(deep indigo, warm gold, ember orange), soft painterly brushwork, gently eerie but child-friendly, '
         'no text, no letters, no logos, no watermark.')

SPECS = {
    'maps': ('1920 × 1080 (16:9), JPG', 'Wide game map background seen from a high three-quarter angle. Keep the middle of the floor open and uncluttered, because character tokens are placed on top. No people.'),
    'portraits': ('1024 × 1024, JPG', 'Square head-and-shoulders portrait, face in the centre so it still reads when cropped to a small circle, plain dark background.'),
    'people': ('1024 × 1024, PNG', 'Square head-and-shoulders character portrait, face in the centre so it still reads when cropped to a small circle, plain dark indigo background.'),
    'monsters': ('1024 × 1024, PNG', 'Square creature portrait, the whole creature centred and filling the frame so it reads when cropped to a small circle, plain dark background.'),
    'mimics': ('1024 × 1024, PNG', 'Square monster portrait, centred, dramatic and scary, plain dark background.'),
    'items': ('1024 × 1024, PNG (transparent background if your tool allows)', 'Single object, centred, game inventory icon, soft rim light, plain dark or transparent background.'),
    'chests': ('1024 × 1024, PNG (transparent background if your tool allows)', 'Single chest, centred, three-quarter view, game icon, plain dark or transparent background.'),
    'hazards': ('1024 × 1024, PNG (transparent background if your tool allows)', 'Single object, centred, game icon, plain dark or transparent background.'),
    'story': ('1200 × 1500 (4:5 portrait), JPG', 'Storybook page illustration with warm parchment tones and a soft vignette, like an old hand-painted fairy-tale book.'),
    'puzzle': ('1024 × 1024, JPG', 'One single unbroken square painting filling the whole image edge to edge. Not cut into tiles, no grid, no lines, no gaps, no puzzle pieces. Spread different details evenly across every part of the picture, and keep the bottom-right corner plain background.'),
}

SECTIONS = [
    ('maps', 'Maps', 'public/maps', 'The background of each place on the TV, the GM map and the phones. There are 35.', [
        ('home', 'Home', 'A cosy ordinary family kitchen at breakfast time, morning sun through the window, an owl tapping at the glass with a sealed letter in its beak, a table with toast and teacups.'),
        ('gringotts', 'Gringotts Wizarding Bank', 'A vast white marble banking hall with tall counters, brass scales and ledgers, chandeliers, and a dark tunnel mouth at the back where mine-cart rails disappear downward.'),
        ('diagon-alley', 'Diagon Alley', 'A crooked cobbled wizarding shopping street, leaning shopfronts with bay windows full of cauldrons, broomsticks, owls in cages and spellbooks, bunting overhead, busy and colourful.'),
        ('ollivanders', 'Ollivanders', 'A narrow, dusty wand shop, thousands of thin wand boxes stacked to the ceiling on tall shelves, a single spindly chair, a ladder, faint magical sparks in the dust.'),
        ('platform', 'Platform Nine and Three-Quarters', 'A steam railway platform with a gleaming scarlet steam engine, clouds of white steam, trunks and owl cages on trolleys, a wrought-iron sign with no lettering.'),
        ('express', 'The Hogwarts Express', 'Inside an old scarlet steam train: a wood-panelled corridor with compartments, a sweets trolley, and at the far end a luggage car where a large painting wrapped in grey cloth leans against the wall.'),
        ('great-hall', 'The Great Hall', 'An enormous stone dining hall with four long wooden tables, hundreds of candles floating in mid-air, and an enchanted ceiling showing a starry night sky, a raised staff table at the far end.'),
        ('entrance-hall', 'Entrance Hall', 'A grand castle entrance hall with huge oak doors, flagstone floor, torches, a sweeping marble staircase, and four giant hourglasses filled with glittering red, yellow, blue and green gems.'),
        ('grand-staircase', 'Grand Staircase', 'A dizzying tower of moving stone staircases criss-crossing in the air, walls covered floor to ceiling in gilded portrait frames, warm torchlight, some stairs mid-swing.'),
        ('gryffindor-common', 'Gryffindor common room', 'A round tower common room in scarlet and gold, squashy armchairs, a roaring fireplace, tapestries of lions, a round portrait doorway.'),
        ('ravenclaw-common', 'Ravenclaw common room', 'An airy round tower room in blue and bronze, arched windows, a domed ceiling painted with stars, bookshelves, a door knocker shaped like an eagle.'),
        ('hufflepuff-common', 'Hufflepuff common room', 'A cosy round basement room in honey-yellow and black, round doorways like a burrow, hanging plants, copper pots, warm wooden furniture.'),
        ('slytherin-common', 'Slytherin common room', 'A long low dungeon room under a lake, green lamps on chains, leather sofas, carved serpents, round windows with dark green water and weeds outside.'),
        ('kitchens', 'The Kitchens', 'A huge vaulted castle kitchen with copper pans, long tables, giant fireplaces, steaming pots and piles of food, a painting of a fruit bowl on the wall.'),
        ('library', 'The Library', 'A tall, silent library with endless dark wooden shelves, rolling ladders, reading tables with green lamps, dust motes in moonlight.'),
        ('restricted-section', 'Restricted Section', 'A locked, roped-off corner of a library, ancient books held shut with iron chains, some faintly glowing or twitching, cobwebs, lantern light.'),
        ('dungeons', 'The Dungeons', 'A cold stone dungeon classroom with cauldrons over small fires, shelves of jars of strange ingredients, dripping walls, eerie green light.'),
        ('charms-classroom', 'Charms classroom', 'A bright classroom with tiered wooden desks, feathers floating in the air, and a tall wobbly stack of books at the front for a very short teacher to stand on.'),
        ('transfiguration-classroom', 'Transfiguration classroom', 'A neat stern classroom with straight rows of desks, a large blackboard, cages of beetles and a teacup halfway turned into a tortoise.'),
        ('defence-classroom', 'Defence classroom', 'A warm, bright classroom crowded with far too many paintings: landscapes, old wizards, a ship in a storm. The painted eyes seem to follow you. Subtly unsettling.'),
        ('trophy-room', 'Trophy Room', 'A long gallery of glass cabinets full of shining cups, shields, medals and plaques, polished floor, one old cup slightly apart from the rest.'),
        ('owlery', 'The Owlery', 'A freezing round stone tower top open to the wind, hundreds of owls on perches, straw and feathers on the floor, glassless windows to a grey sky.'),
        ('astronomy-tower', 'Astronomy Tower', 'The highest tower top at night, a stone parapet, brass telescopes and star charts, a huge starry sky and the castle roofs far below.'),
        ('hospital-wing', 'Hospital Wing', 'A long quiet infirmary with rows of white iron beds and screens, tall windows; some beds hold still, grey, colourless sleeping students. Sad and hushed.'),
        ('room-of-requirement', 'Room of Requirement', 'A cavernous hidden room piled high with forgotten things: furniture, trunks, broken brooms, statues, towering into the dark. One corner glows faintly.'),
        ('undercroft', 'The Undercroft', 'A vast dark chamber deep beneath the castle, stone pillars, dripping water, old paint smeared on the walls, and a huge round door carved with a coiled serpent.'),
        ('courtyard', 'The Courtyard', 'A stone castle courtyard with arched cloisters, a fountain, autumn leaves, benches, soft daylight.'),
        ('greenhouses', 'Greenhouses', 'Warm, steamy glass greenhouses packed with strange magical plants in pots, earmuffs hanging on hooks, one pot with a screaming root peeking out.'),
        ('quidditch-pitch', 'Quidditch Pitch', 'A magical sports pitch seen from above, tall striped spectator towers, three tall golden hoops on poles at each end, windswept grass.'),
        ('black-lake', 'The Black Lake', 'A dark still lake beside the castle, mist on the water, reeds and rocks on the shore, a huge shadowy tentacle just breaking the surface.'),
        ('hagrids-hut', 'The old gamekeeper’s hut', 'A stone hut with a giant-sized wooden door and a smoking chimney, enormous pumpkins in the garden, a crossbow by the door, the forest edge behind.'),
        ('forbidden-forest', 'Forbidden Forest', 'A dark, ancient forest with huge twisted trees, thick roots, mist, faint glowing eyes between the trunks, moonlight through branches.'),
        ('hogsmeade', 'Hogsmeade Village', 'A snowy little wizarding village street, thatched rooftops, warm shop windows full of sweets and jokes, lanterns, people-free cobbles.'),
        ('three-broomsticks', 'The Three Broomsticks', 'A cosy crowded village inn with a crackling fire, wooden beams, tankards of foaming drink on the tables, a long bar.'),
        ('shrieking-shack', 'The Shrieking Shack', 'Inside a crooked, boarded-up haunted shack, broken furniture, torn wallpaper, claw marks on the floor, moonlight through the boards.'),
    ]),
    ('portraits', 'Family portraits', 'public/portraits', 'The six families on the TV, the family picker and as each player’s token on the map. Swap [boy/girl] for the player who takes that family.', [
        ('blackwood', 'Blackwood', 'An 11-year-old [boy/girl] from an old, rich wizarding family, dark neatly combed hair, elegant black robes with a silver brooch, confident, faintly haughty smile, a gilded portrait frame behind.'),
        ('sinclair', 'Sinclair', 'An 11-year-old [boy/girl] from a family of dark-wizard hunters, determined eyes, short practical hair, sturdy robes with a scuffed leather wand holster, brave and serious.'),
        ('fenwick', 'Fenwick', 'An 11-year-old [boy/girl] from a joke-shop family, messy hair, mischievous grin, a smudge of soot on one cheek, a fizzing firework sparkler and a folded old paper map peeking from a pocket.'),
        ('thornbury', 'Thornbury', 'An 11-year-old [boy/girl] from a family of magical-creature breeders in the hills, windswept hair with a feather caught in it, freckles, warm kind eyes, a well-worn woollen jumper under robes.'),
        ('quill', 'Quill', 'An 11-year-old [boy/girl] from a non-magical family, wide curious eyes, round glasses, brand-new robes slightly too big, clutching a fresh spellbook, a faint shiver of something watching behind them.'),
        ('marlowe', 'Marlowe', 'An 11-year-old [boy/girl] from a fallen noble family, sharp features, guarded expression, faded hand-me-down robes, an old iron key with a serpent on it on a cord round the neck.'),
    ]),
    ('people', 'People', 'public/art/people', 'Everyone the players can meet. They show on the map and in the Here tab.', [
        ('headmaster', 'The Headmaster', 'A very old, kind headmaster with a long white beard, half-moon spectacles, deep plum robes with silver stars, tired eyes hiding worry.'),
        ('flitwick', 'Professor Flitwick', 'A very short, cheerful elderly charms professor with round spectacles, a neat silver beard and a huge delighted smile, standing on a wobbly stack of books, sparks dancing from his wand.'),
        ('grimsby', 'Professor Grimsby', 'A thin, grey, sour-faced potions master with narrow eyes, a stained dark apron over black robes, a faint wisp of yellow smoke from a vial in his hand.'),
        ('longbottom', 'Professor Longbottom', 'A kind, round-faced herbology professor in his forties with a shy smile, soil-stained apron and gloves, a small leafy plant in a pot in his hands.'),
        ('ashgrove', 'Professor Ashgrove', 'A handsome, warm, smiling defence teacher with neat auburn hair and a tweed waistcoat, holding a paintbrush. Look closely: a single fleck of wet paint glistens in one eye.'),
        ('vance', 'Professor Vance', 'A crisp, exact transfiguration professor, a woman with sharp cheekbones, a tight silver bun, emerald robes, a wand held perfectly straight.'),
        ('scamander', 'Professor Scamander', 'A dreamy, distracted magical-creatures professor, a woman with wild sandy hair and a patched coat, a battered leather suitcase with something bumping inside it, a small creature on her shoulder.'),
        ('hooch', 'Madam Hooch', 'A brisk, fierce flying instructor with short windswept grey hair, flying goggles pushed up on her head, a whistle round her neck, holding a broomstick.'),
        ('filch', 'Filch', 'A grumpy, hunched old castle caretaker with a lantern and a ring of iron keys, scruffy grey hair, a skinny dusty cat at his feet.'),
        ('peeves', 'Peeves', 'A gleeful, floating little poltergeist with a wicked crooked grin, slightly transparent, wearing a crooked hat and mismatched socks, juggling chalk and inkpots.'),
        ('ghost', 'A ghost', 'A sad, polite, old-fashioned ghost of a gentleman in a ruffled collar and long coat, pale silver-blue and see-through, floating, hat in hand.'),
        ('house-elf', 'House-elf', 'A small, eager kitchen helper creature with huge bat-like ears and big round eyes, wearing a neatly tied tea towel like a toga, holding a silver tray, bowing.'),
        ('centaur', 'Centaur', 'A proud, mysterious centaur in a moonlit forest, long dark hair, a bow over the shoulder, eyes turned up to the stars.'),
        ('sinclair-prefect', 'Prefect Sinclair', 'A tired but brave 16-year-old student prefect, hair in a practical ponytail, a shiny prefect badge on her robes, a determined, protective look.'),
        ('rival', 'Cassius Thorne', 'A smug 13-year-old student with slicked-back pale hair and a lazy smirk, flipping a gold coin, green and silver scarf.'),
        ('collector', 'Wren Ashby', 'A quick, clever 14-year-old student with ink-stained fingers, round spectacles pushed up on her head, a blue and bronze scarf, fanning out a hand of collectible trading cards.'),
        ('painting', 'The covered painting', 'A large ornate gilded frame draped in a grey cloth, one corner of the cloth slipped, revealing a single painted eye looking out. Ominous.'),
        ('librarian', 'The librarian', 'A thin, severe librarian with a long nose and sharp eyes behind spectacles, finger raised to her lips for silence, an armful of old books.'),
        ('matron', 'The matron', 'A brisk, warm school nurse with a white cap and apron, rosy tired cheeks, holding a steaming bottle of medicine.'),
        ('ollivander', 'Mr Ollivander', 'An old, wide-eyed wandmaker with silvery eyes and wispy white hair, holding out a slim wand box, appearing silently from the shadows of his shop.'),
        ('goblin', 'Gringotts goblin', 'A sharp-faced goblin bank clerk with long fingers, pointed ears and a narrow suspicious stare, a quill and a jeweller’s eyeglass.'),
        ('trolley-witch', 'The trolley witch', 'A cheerful, dimpled old witch in a cardigan pushing a sweets trolley piled with chocolate and treats, on a moving train.'),
        ('landlady', 'The landlady', 'A loud, curvy, motherly village innkeeper with rosy cheeks and curly hair, pouring a foaming tankard, a cheeky gossiping smile.'),
        ('victim', 'A drained student', 'A young student lying asleep, completely grey from head to toe as if painted in ash, colourless robes, peaceful but eerie.'),
    ]),
    ('monsters', 'Monsters', 'public/art/monsters', 'Everything the players can fight. They show on the map with a health bar.', [
        ('cornish-pixie', 'Cornish Pixie', 'A tiny electric-blue pixie with insect wings and a shrieking, mischievous face, mid-flight, pulling a face.'),
        ('devils-snare', 'Devil’s Snare', 'A writhing mass of dark green vines and tendrils reaching out of the darkness, coiling, shrinking from a ray of light.'),
        ('boggart', 'Boggart', 'A shapeshifting shadow creature bursting out of an old wardrobe, half-formed, swirling between several frightening silhouettes.'),
        ('rival-duelist', 'Dueling Club rival', 'An older student in dueling stance, wand raised, cocky grin, robes swirling, a spark of magic at the wand tip.'),
        ('paint-wraith', 'Paint Wraith', 'A ghostly figure made of dripping, smeared oil paint, swirling colours for a body, hollow eyes, clawing hands trailing brushstrokes.'),
        ('acromantula', 'Acromantula', 'A huge hairy spider the size of a horse with many gleaming eyes and clicking pincers, in a dark misty forest.'),
        ('troll', 'Mountain Troll', 'A huge, lumbering grey troll with a tiny head, thick skin and a giant wooden club, dim-witted snarl.'),
        ('ashgrove-possessed', 'Ashgrove (possessed)', 'The warm smiling teacher, now possessed: eyes made of swirling wet paint, paint dripping from his face and hands, cracked like an old oil painting, terrifying.'),
        ('corvin-vale', 'Corvin Vale', 'An ancient painter wizard half stepping out of a giant canvas, his body made of thick oil paint and canvas, a brush like a wand, beautiful and terrible, the final boss.'),
    ]),
    ('mimics', 'Mimics (revealed)', 'public/art/mimics', 'What the mimics look like after they spring. Until then they look like an ordinary chest or person.', [
        ('hungry-trunk', 'The Hungry Trunk', 'A battered old travelling trunk that has sprung open into a huge mouth full of jagged teeth and a long tongue, belts and buckles snapping, half-swallowed books and potions inside.'),
        ('painted-double', 'The Painted Double', 'A copy of a person made of wet paint, the face sliding and smearing, a perfect smile painted on, brushstrokes where the eyes should be.'),
    ]),
    ('items', 'Items', 'public/art/items', 'Things players pick up, buy or carry. They show on the map, in the bag and in the shops.', [
        ('wand', 'Wand (every wand)', 'A slender hand-carved wooden magic wand with a carved handle, a faint glow at the tip.'),
        ('chocolate-frog', 'Chocolate Frog', 'A chocolate frog in a five-sided purple and gold box with the lid open, the frog mid-leap.'),
        ('pumpkin-pasty', 'Pumpkin Pasty', 'A golden crimped pumpkin pastry, steaming, on a paper napkin.'),
        ('pepperup', 'Pepperup Potion', 'A small round potion bottle of bubbling red-orange liquid with steam puffing out of the cork.'),
        ('wiggenweld', 'Wiggenweld Potion', 'A healing potion in a heart-shaped glass bottle of glowing green liquid with a cork.'),
        ('focus-draught', 'Focus Draught', 'A slim crystal vial of swirling violet liquid with tiny stars inside.'),
        ('bertie-botts', 'Bertie Bott’s Beans', 'A small striped paper bag spilling jelly beans of every colour, some odd-looking.'),
        ('felix', 'Felix Felicis', 'A tiny teardrop flask of liquid gold that glitters and shimmers with luck.'),
        ('remembrall', 'Remembrall', 'A glass ball the size of a large marble, filled with swirling smoke that is turning red.'),
        ('extendable-ears', 'Extendable Ears', 'A long flesh-coloured string with a rubbery ear on the end, coiled.'),
        ('sneakoscope', 'Pocket Sneakoscope', 'A small glass spinning top that glows and whirls when someone lies.'),
        ('mandrake-leaf', 'Mandrake leaf', 'A tufted green leaf on a knobbly root with a tiny grumpy face.'),
        ('creature-treats', 'Creature treats', 'A small cloth pouch of crunchy animal treats tied with string, some spilling out.'),
        ('serpent-key', 'Serpent key', 'An old heavy iron key whose handle is a coiled serpent with green gem eyes.'),
        ('map-half', 'Half of the Marauder’s Map', 'Half of an old folded parchment map torn down the middle, inked corridors and tiny footprints, the torn edge ragged.'),
        ('vale-page', 'Torn page about Corvin Vale', 'A brittle torn page from an old book with a faded sketch of a painter and one line underlined so hard the paper ripped.'),
        ('restorative-draught', 'Restorative Draught', 'A tall glowing potion of warm white-gold light, like bottled sunrise.'),
        ('frog-card', 'Rare Chocolate Frog card', 'A shiny rare collectible wizard trading card with a gold foil border and a moving portrait.'),
        ('ring-clue-serpent', 'Scratched note (first ring)', 'A scrap of parchment with a serpent symbol scratched into it.'),
        ('ring-clue-moon', 'Star chart (second ring)', 'A small rolled star chart with the moon circled.'),
        ('ring-clue-owl', 'Feathered card (last ring)', 'A small card with an owl feather tucked into it.'),
        ('diary-page', 'Page of Vale’s diary', 'An old diary page covered in strange glowing runes and dried paint stains.'),
        ('stolen-jars', 'Stolen ingredient jars', 'A cluster of glass jars of potion ingredients: eyes, roots, beetles, with scrawled spiky labels.'),
        ('robes-plain', 'Second-hand robes', 'Patched, faded black school robes on a hanger.'),
        ('robes-standard', 'Standard school robes', 'Plain neat black school robes on a hanger.'),
        ('robes-tailored', 'Tailored robes', 'Fine tailored black robes with silver buttons and silk lining.'),
        ('robes-dragonhide', 'Dragonhide-lined robes', 'Heavy black robes lined with gleaming dark dragon scales.'),
        ('toad', 'Toad', 'A plump, warty, grumpy-looking pet toad.'),
        ('rat', 'Rat', 'A small scruffy pet rat with a pink nose and whiskers.'),
        ('cat', 'Cat', 'A sleek clever-eyed pet cat sitting upright.'),
        ('owl', 'Owl', 'A fluffy snowy pet owl with big amber eyes.'),
        ('bowtruckle', 'Bowtruckle', 'A tiny twig-like stick creature with leaf hair and bright eyes, clinging to a wand.'),
        ('kneazle', 'Kneazle', 'A spotted cat-like magical creature with huge ears and a lion-like tufted tail.'),
        ('niffler', 'Niffler', 'A small fluffy black creature with a duck-like snout, clutching gold coins.'),
        ('cauldron-pewter', 'Pewter cauldron', 'A small plain grey pewter cauldron.'),
        ('cauldron-brass', 'Brass cauldron', 'A polished brass cauldron.'),
        ('cauldron-gold', 'Gold cauldron', 'A gleaming solid gold cauldron with ornate handles.'),
        ('books-used', 'Used book set', 'A stack of battered second-hand spellbooks with scribbled notes sticking out.'),
        ('books-new', 'New book set', 'A neat stack of brand-new spellbooks tied with string.'),
        ('books-annotated', 'Annotated book set', 'A stack of spellbooks bristling with ribbons and margin notes, one open with glowing handwriting.'),
    ]),
    ('chests', 'Chests', 'public/art/chests', 'Chests players can try to open. The Hungry Trunk looks exactly like the locked chest until it bites.', [
        ('small-chest', 'Small chest', 'A small plain wooden chest with a simple latch.'),
        ('locked-chest', 'Locked chest', 'A sturdy iron-banded wooden chest with a big padlock.'),
        ('ancient-chest', 'Ancient chest', 'An ancient carved stone and bronze chest with runes and moss, a strange keyhole.'),
        ('cursed-chest', 'Cursed chest', 'A black coffin-shaped chest with green smoke seeping from the cracks and a skull clasp.'),
    ]),
    ('hazards', 'Hazards', 'public/art/hazards', 'Things in the finale the players can use against the enemy.', [
        ('paint-jars', 'Shelf of paint jars', 'A rickety wooden shelf crowded with jars of thick oil paint in every colour, some tipping over.'),
        ('cracked-mirror', 'Cracked mirror', 'A tall ornate mirror with a long crack, reflecting a strange light.'),
        ('braziers', 'Cold braziers', 'A pair of iron fire braziers on stands, cold and dark, ready to be lit.'),
        ('ritual-circle', 'Ritual circle', 'A glowing circle of painted runes on a stone floor, faint red light rising from it.'),
        ('canvas', 'Vale’s empty canvas', 'A huge empty canvas on a wooden easel, the surface rippling like water, paint brushes scattered around.'),
        ('pillar', 'Cracked pillar', 'A thick stone pillar with a deep crack running up it, dust falling, ready to topple.'),
    ]),
    ('story', 'Storybook pages', 'public/story', 'The six pictures in the red storybook during the opening (file names page-1.jpg to page-6.jpg).', [
        ('page-1', 'Page 1', 'Three hundred years ago: a painter in an old candlelit studio painting a portrait so lifelike its subject seems to breathe, admirers gasping.'),
        ('page-2', 'Page 2', 'The painter, now old and afraid, standing before a huge unfinished self-portrait of himself young and beautiful, an hourglass running out beside him.'),
        ('page-3', 'Page 3', 'Dawn in an old castle corridor: students lying grey and silent as if painted in ash, the painted eyes of portraits watching.'),
        ('page-4', 'Page 4', 'A noble wizarding family raising their wands together, sealing a furious painter inside his own canvas in a burst of light.'),
        ('page-5', 'Page 5', 'A painting wrapped in grey cloth being loaded onto a scarlet steam train at night, steam curling, a single eye glinting under the cloth.'),
        ('page-6', 'Page 6', 'Six sealed letters with wax seals flying through the sky towards six different houses, a castle on a hill in the distance.'),
    ]),
    ('puzzle', 'Puzzle picture', 'public/puzzles', 'The Scrambled Portrait puzzle (file name portrait.jpg).', [
        ('portrait', 'The Scrambled Portrait', 'An old oil portrait of a young painter in a velvet coat holding a brush, a coiled serpent carved into the gold frame, a small window behind him showing a lake, a candle on the left, a paint palette held against his chest.'),
    ]),
]


def file_for(folder_key, fid):
    ext = 'jpg' if folder_key in ('maps', 'portraits', 'story', 'puzzle') else 'png'
    base = {'maps': 'public/maps', 'portraits': 'public/portraits', 'story': 'public/story', 'puzzle': 'public/puzzles'}.get(folder_key, f'public/art/{folder_key}')
    return f'{base}/{fid}.{ext}'


def full_prompt(key, text):
    return f'{text} {SPECS[key][1]} {STYLE}'
