def day_table(rows):
    return ('table', ['Block', 'What happens', 'Where'], rows, [28, 106, 36])


BLOCKS = [
    ('chapter', 'Part 2', 'The Week', 'Seven days, five blocks a day, and a ritual at the end of it.'),
    ('h2', 'How a day runs'),
    ('table', ['Block', 'What the players do', 'Your job'], [
        ['Morning class', 'Go to class and play the minigame. Or skip it, and miss the lesson.', 'Start the class minigame.'],
        ['Lunch', 'Two things: explore, talk to people, follow leads.', 'Read beats. Give quests on offer. People and clues place themselves.'],
        ['Afternoon class', 'Second class of the day.', 'Start the class minigame.'],
        ['Free time', 'Three things: explore, quests, puzzles, the library.', 'Same as Lunch.'],
        ['Curfew', 'Two things: sneak around (risky) or rest.', 'Spin <b>Out after curfew</b> for anyone caught moving.'],
    ], [30, 80, 60]),
    ('p', 'When you press <b>Advance time</b> past Curfew, a new morning begins: every student is restored to full HP and mana, and once-a-day abilities recharge. That is the long rest. If the party wants to keep going through the night, the clock does not care.'),
    ('gm', 'Every <b>Advance time</b> also moves the whole castle: staff, prefects, ghosts and Peeves go to their places for the new block, and that block’s clues, chests, hazards and monsters appear on the map. The tables below say what happens; the <b>Conversation Book</b> says exactly who is where. See <b>The living castle</b> in Part 3.'),
    ('h3', 'Running a class'),
    ('list', [
        'When the clock reaches a class, the Day &amp; class tab shows the class, professor, classroom and what it teaches.',
        'Tick who is attending. Anyone who is elsewhere (on a quest, in detention, asleep) misses it.',
        'Press <b>🎮 Start class minigame</b>. The professor and the students move into the classroom on the map, and every attending phone switches to the game.',
        'Each student gets two attempts. Passing teaches them the spell or item and gives 10 XP automatically. Failing twice means no lesson.',
        'Press <b>End class</b> when everyone is done.',
    ]),
    ('read', 'The professor sweeps in, and the room falls quiet. “Wands out,” they say. “Today you are going to learn something that might one day save your life. Most of you will get it wrong the first time. That is allowed. Getting it wrong twice is less allowed.”'),
    ('h3', 'Running free time'),
    ('p', 'Free blocks are where the story lives. Look at the TV with the players: the panel on the right lists what they can do here, the people present and the paths out. Ask what they want to do, then do it for them on the map.'),
    ('wait', '“It’s lunchtime. You have about an hour before class. Where do you go?” Let them split up if they want. Move each group separately with the Move tick boxes.'),
    ('tip', 'If the table goes quiet, use a nudge: a ghost drifts past with gossip, Cassius picks a fight, or spin <b>Hogwarts surprises</b>.'),

    ('h2', 'Day 1: Welcome to Hogwarts'),
    day_table([
        ['Morning class', '<b>Charms</b> with Professor Flitwick. Teaches <b>Lumos</b>. Minigame: Wand Motion.', 'Charms classroom'],
        ['Lunch', 'Prefect Sinclair finds the group and offers <b>Keep an Eye Out</b>.', 'Great Hall'],
        ['Afternoon class', '<b>Potions</b> with Professor Grimsby. Teaches <b>Pepperup Potion</b> (2). Minigame: Stir Timing.', 'Dungeons'],
        ['Free time', 'Grimsby storms past furious: his store cupboard was raided. Offer <b>Stolen Ingredients</b>.', 'Dungeons'],
        ['Curfew', '<b>Beat:</b> a covered painting is hung in a corridor near the Undercroft.', 'Anywhere'],
    ]),
    ('read', 'Professor Grimsby does not look up when you come in. “Sit. Open your books. If anyone’s cauldron explodes, they clean it up themselves.” He is thin and grey and smells faintly of sulphur. Nobody likes him. You can tell he likes it that way.'),
    ('h3', 'Curfew beat'),
    ('read', 'Late that night, two figures carry something large and wrapped down a stairway that most students do not know exists. They hang it in a dead-end corridor deep under the castle, below the dungeons. When they leave, the corridor is very, very quiet. Then the cloth stirs, though there is no wind.'),
    ('p', 'If the Quill is awake, they wake with a jolt from a dream of a painted eye. Nobody else feels a thing.'),

    ('h2', 'Day 2: The first victim'),
    day_table([
        ['Morning class', '<b>Herbology</b> with Professor Longbottom. Teaches Mandrake care (1 Mandrake leaf). Minigame: Mandrake Repotting.', 'Greenhouses'],
        ['Lunch', 'Ashgrove chats warmly with students and shows off his portraits. Everyone loves him.', 'Defence classroom'],
        ['Afternoon class', '<b>Defence Against the Dark Arts</b> with Professor Ashgrove. Teaches <b>Expelliarmus</b>. Minigame: Duel Reflexes.', 'Defence classroom'],
        ['Free time', 'Dueling Club sign-ups with Flitwick: offer <b>Dueling Club Champion</b>.', 'Great Hall'],
        ['Curfew', '<b>Beat (cliffhanger):</b> Prefect Sinclair is found drained outside Ravenclaw Tower.', 'Ravenclaw common room'],
    ]),
    ('read', 'Professor Longbottom is already up to his elbows in soil when you arrive, laughing at something a plant has just done. “Earmuffs on, everyone! These are Mandrakes. Their cry won’t kill you at this age, but it’ll ruin your afternoon. Gently does it.”'),
    ('read', 'Professor Ashgrove’s classroom is warm and bright and full of paintings: landscapes, old wizards, a ship in a storm. He is the kind of teacher who remembers your name on the first day. “Defence is not about fighting,” he says. “It is about making sure the fight never reaches you. Now. Wands up.”'),
    ('h3', 'Curfew beat: the cliffhanger'),
    ('gm', 'Move any students who are out to <b>Ravenclaw common room</b> (or wherever the scream would reach them). Place <b>Prefect Sinclair</b> on the map. After the reveal, pin the clue <b>“Every portrait near an attack had gone silent”</b> under <b>The covered painting</b> on the TV shows tab when they notice it.'),
    ('read', [
        'A scream echoes down the corridor outside Ravenclaw Tower. By the time you get there, a crowd of students in pyjamas is standing in a ring around someone lying very still on the flagstones.',
        'It is the Sinclair prefect. Her eyes are open. She is breathing. But she is grey, all of her, as if someone has painted her in shades of ash. Her wand lies beside her hand, and when a teacher picks it up, it crumbles like charcoal.',
        'Along the corridor walls, every portrait is empty. Their frames hold only painted backgrounds. The people in them have gone somewhere else.',
    ]),
    ('wait', 'Look at the Sinclair player. “What do you do?” Then stop. That is the end of session one.'),

    ('h2', 'Day 3: Shadows in the library'),
    ('tip', 'Start session two with a recap. Ask the players to tell you what has happened so far, in their own words. Fill in only what they forget.'),
    day_table([
        ['Morning class', '<b>Transfiguration</b> with Professor Vance. Teaches <b>Avifors</b>. Minigame: Matching Pairs.', 'Transfiguration classroom'],
        ['Lunch', '<b>Beat:</b> a second student is drained near the library. Longbottom offers <b>Wake the Sleepers</b>.', 'Library'],
        ['Afternoon class', '<b>Care of Magical Creatures</b> with Professor Scamander. Teaches creature handling (2 Creature treats). Minigame: Befriend the Beast. Offer <b>Where is Bramble?</b>', 'Gamekeeper’s hut'],
        ['Free time', 'The library opens up. Place the Restricted Section’s first diary page if you are running the Painter’s Bargain.', 'Library'],
        ['Curfew', 'Anyone sneaking out spins <b>Out after curfew</b>. Filch means detention, and that starts <b>The Old Cup</b>. Hide <b>The Hungry Trunk</b> in the Trophy Room as a Locked chest.', 'Anywhere'],
    ]),
    ('read', 'The second victim is a fourth-year, slumped against the library shelves with a book still open in her lap. Grey, all of her. The librarian is white with shock. The portraits in this corridor are silent too, and one of them has a smear of fresh paint across its frame, as if something climbed out in a hurry.'),
    ('gm', 'Clues to pin now (TV shows tab), when the players find them: <b>Grimsby’s store cupboard was raided</b> (under Grimsby), <b>Every portrait near an attack had gone silent</b> (under the painting).'),
    ('read', 'Professor Scamander keeps a battered old suitcase by her feet at all times. Something inside it occasionally thumps. “Creatures are not dangerous,” she says. “People who do not understand them are dangerous. Today we learn to understand.”'),

    ('h2', 'Day 4: The missing page'),
    day_table([
        ['Morning class', '<b>Potions</b> with Grimsby. Teaches <b>Wiggenweld Potion</b> (2). Minigame: Stir Timing, harder.', 'Dungeons'],
        ['Lunch', 'Cassius is seen in the courtyard with half of an old map. The Fenwick should get <b>The Other Half</b>.', 'Courtyard'],
        ['Afternoon class', '<b>Flying Lessons</b> with Madam Hooch. Teaches broom flying. Minigame: Broom Dodge.', 'Quidditch Pitch'],
        ['Free time', '<b>Beat:</b> the only page about Corvin Vale vanishes from the Restricted Section, unless the players already took it.', 'Restricted Section'],
        ['Curfew', 'A good night for the Torch Wall or the Moving Staircases if the party is exploring.', 'Anywhere'],
    ]),
    ('read', 'Madam Hooch blows her whistle hard enough to rattle the stands. “Right hand over the broom and say UP! Not up, not please, UP! And if anyone flies into the hoops, I am not picking you up.”'),
    ('gm', 'Clues to pin as found: <b>Ashgrove’s classroom has more paintings every day</b>, <b>Filch has keys to every corridor</b>, <b>Cassius was seen with half of an old map</b>, and <b>A page about Corvin Vale</b> if they reach it in time. Place it as an item, <b>Torn page about Corvin Vale</b>, in the Restricted Section early in the day.'),
    ('read', 'The page is old and brittle. Most of it is about a painter named Corvin Vale, who lived three hundred years ago and painted portraits so lifelike that people said his subjects sometimes left their frames. In his last years, he became obsessed with one idea: that a painting never grows old. The final line has been underlined so hard that the quill tore through the paper. “I will finish myself.”'),

    ('h2', 'Day 5: Suspicion'),
    day_table([
        ['Morning class', '<b>Charms</b> with Flitwick. Teaches <b>Alohomora</b>. Minigame: Wand Motion, harder. Students who skip this will struggle with the Time-Turner and chests.', 'Charms classroom'],
        ['Lunch', 'Grimsby is seen carrying armfuls of ingredients to his office. Suspicious?', 'Dungeons'],
        ['Afternoon class', '<b>Defence</b> with Ashgrove. Teaches <b>Protego</b>. Minigame: Duel Reflexes, harder.', 'Defence classroom'],
        ['Free time', 'The Room of Requirement can appear if they think to look. Offer <b>The Turning Lock</b>.', 'Grand Staircase'],
        ['Curfew', '<b>Beat:</b> Grimsby is caught standing over a third victim.', 'Dungeons'],
    ]),
    ('h3', 'Curfew beat: the red herring'),
    ('read', 'In the dungeon corridor, a third student lies grey and still. Kneeling over them, wand raised, is Professor Grimsby. When he sees you, his face goes from shock to fury. “Back to your common rooms! Now!” In his other hand is a small bottle of something glowing faintly gold.'),
    ('gm', 'Pin <b>Grimsby was found standing over the third victim</b> under Grimsby. Do not clear him yet. If the players investigate his office or the bottle, give them <b>Grimsby was secretly brewing a draught to wake the victims</b>, which clears him.'),
    ('tip', 'This is the moment the players will want to accuse Grimsby. Let them. Their accusation is wrong, and finding that out is half the fun. Use the suspect board: mark him <b>Accused</b>, then <b>Cleared</b> when the truth comes out. This is the end of session two.'),

    ('h2', 'Day 6: Hogsmeade'),
    day_table([
        ['Morning class', 'No classes. Hogsmeade visit. Open the shops if you like.', 'Hogsmeade'],
        ['Lunch', 'The Three Broomsticks: rumours about a painter, and a ghost who saw “a figure step out of a frame”.', 'Three Broomsticks'],
        ['Afternoon class', 'No classes. The Shrieking Shack holds a diary page for the Painter’s Bargain.', 'Shrieking Shack'],
        ['Free time', '<b>Beat:</b> Ashgrove’s eyes flicker with paint. The truth can come out tonight.', 'Defence classroom'],
        ['Curfew', 'The covered painting may whisper its bargain to one student. Offer <b>The Painter’s Bargain</b>.', 'Undercroft corridor'],
    ]),
    ('read', 'Hogsmeade is all snowy roofs and warm windows. The sweet shop smells of sugar and chocolate. In the Three Broomsticks, the landlady puts down two frothing Butterbeers and leans in. “Strange business up at the school, I hear. Kids going grey. My gran used to tell a story about a painter who did that. Vale, his name was. Don’t go looking for him, dears.”'),
    ('h3', 'Free time beat: Ashgrove’s eyes'),
    ('read', 'Ashgrove is marking essays alone in his classroom when you pass the door. He looks up and smiles his warm smile, and for just a moment, his eyes are not eyes. They are brushstrokes: thick, wet, swirling paint. He blinks, and they are ordinary again. “Can I help you?” he asks. Every painting in the room is watching you.'),
    ('gm', 'Pin <b>Ashgrove’s eyes looked like brushstrokes</b> and, if they look closely at his sleeve, <b>Flecks of wet paint on Ashgrove’s sleeve</b>. If the players put it together tonight, let them confront him. If not, it all comes out on Day 7.'),

    ('h2', 'Day 7: The seventh night'),
    day_table([
        ['Morning class', '<b>Transfiguration</b> with Vance. Teaches <b>Incendio</b>. This is the spell that burns Paint Wraiths and Vale’s canvas.', 'Transfiguration classroom'],
        ['Lunch', 'Ashgrove does not appear at lunch. His classroom is locked. His paintings are gone.', 'Great Hall'],
        ['Afternoon class', 'Classes cancelled. The castle is on lockdown. Teachers patrol the corridors.', 'Common rooms'],
        ['Free time', 'The last chance to prepare: brew, rest, find the Time-Turner, solve the Trials.', 'Anywhere'],
        ['Curfew', '<b>Beat: the ritual.</b> If Vale is not stopped before this block ends, he walks free and the game is lost.', 'The Undercroft'],
    ]),
    ('read', 'At breakfast, the Headmaster stands and the hall falls silent. “As of this afternoon, the castle is closed. Students will remain in their common rooms. No exceptions.” Every portrait in the Great Hall is empty. Somewhere far below, so deep you feel it in your feet more than hear it, something is humming.'),
    ('p', 'Turn to Part 6, the Finale, when the players head for the Undercroft. The Day &amp; class tab warns you when you reach the final block.'),
    ('tip', 'If the players use the Time-Turner, everyone returns to Day 1 morning with all their XP, spells and items, and you replay the week with them knowing everything. The beats happen again unless they stop them. It can only happen once.'),
]
