BLOCKS = [
    ('chapter', 'Part 3', 'Running the Systems', 'The rules in one place, for when a player asks “can I…?”'),
    ('h2', 'Checks'),
    ('p', 'When a player tries something that could fail, ask for a check: a d20 plus one stat bonus, against a difficulty. They roll on the <b>Dice</b> tab (pick d20 and the stat). The result appears on the TV.'),
    ('table', ['Difficulty', 'DC', 'Example'], [
        ['Very easy', '5', 'Climbing a low wall, remembering a professor’s name'],
        ['Easy', '10', 'Sneaking past a dozing portrait, calming a nervous owl'],
        ['Medium', '13', 'Picking a lock, lying to a prefect, finding a book fast'],
        ['Hard', '16', 'Sneaking past Filch, reading an ancient rune'],
        ['Very hard', '19', 'Lying to the Headmaster, outrunning an Acromantula'],
    ], [28, 14, 128]),
    ('table', ['Stat', 'Use it for'], [
        ['STR', 'Forcing doors, carrying, holding on, punching'],
        ['DEX', 'Sneaking, dodging, flying, picking locks, quick hands'],
        ['CON', 'Resisting poison, cold, curses, staying awake'],
        ['INT', 'Potions, research, puzzles, remembering lessons, ancient chests'],
        ['WIS', 'Noticing things, reading people, creatures, sensing danger'],
        ['CHA', 'Persuading, lying, charming teachers, bluffing Filch'],
    ], [20, 150]),
    ('list', [
        '<b>Advantage:</b> roll two d20s and keep the higher. Give it when something helps: a good plan, the right spell, a friend helping.',
        '<b>Disadvantage:</b> roll two and keep the lower. Give it when something hinders: darkness, panic, a broken wand.',
        '<b>Natural 20</b> always succeeds in a fight. <b>Natural 1</b> always fails. Outside fights, describe something wonderful or disastrous.',
    ]),

    ('h2', 'Fights and duels'),
    ('list', [
        'Place monsters on the map (Table tab, <b>Place on this map</b>, Monsters). Only students standing in that place take part.',
        'Press <b>Start fight</b>. Everyone rolls initiative automatically and the TV shows the turn order.',
        '<b>A student’s turn:</b> their phone glows “Your turn!”. On the Dice tab they choose a spell or Improvised attack, pick a target, roll d20 to hit against the target’s Defence, then roll the spell’s own damage die. The monster’s HP drops by itself.',
        '<b>A monster’s turn:</b> press <b>Select</b> on it, choose who it attacks, press <b>Attack</b>. The app rolls against that student’s Defence.',
        'Press <b>Next turn</b> to move on. When it is over, <b>End and share XP</b> removes the beaten monsters and gives their XP to everyone who fought.',
        'A student at 0 HP is <b>knocked out</b>, not dead. They are first-years. A potion or a new morning brings them back.',
    ]),
    ('read', 'Describe the hit, not the numbers. Not “you deal six damage” but: “Your Stupefy catches it square in the chest, and it skids back across the flagstones, hissing.”'),
    ('h3', 'Spells'),
    ('table', ['Spell', 'Mana', 'Roll', 'Does', 'Learned'], [
        ['Improvised attack', '0', 'd20 + STR, then d4', 'Punch, kick, throw something', 'Always'],
        ['Lumos', '1', 'none', 'Light; reveals invisible ink; Devil’s Snare hates it', 'Day 1 Charms'],
        ['Avifors', '2', 'd4', 'Birds distract for that many rounds', 'Day 3 Transfiguration'],
        ['Alohomora', '2', 'd20 + INT check', 'Opens locks; advantage on chests', 'Day 5 Charms'],
        ['Protego', '3', 'd6', 'Blocks that much damage from the next attack', 'Day 5 Defence'],
        ['Expelliarmus', '3', 'd20 + DEX to hit', 'On a hit, the target’s next attack misses', 'Day 2 Defence'],
        ['Stupefy', '4', 'd20 + INT, then d8', 'Damage (plus spell damage bonus)', 'Sinclairs start with it'],
        ['Incendio', '5', 'd20 + INT, then d10', 'Damage; burns Paint Wraiths and canvas', 'Day 7 Transfiguration'],
        ['Avada Kedavra', '10', 'd20 + CHA to hit', 'Kills outright; bosses take 20', 'Secret (see Part 4)'],
    ], [30, 12, 34, 62, 32]),
    ('h3', 'Teaching other spells'),
    ('gm', '<b>✨ Spells</b> tab: pick a student, then <b>Teach</b> any spell. It appears on their Dice tab with its own dice, ready to cast. <b>Remove</b> takes it away. Tick <b>Announce on the TV</b> for a public moment, or leave it off for secrets. For Expecto Patronum, type their Patronus form first (otter, stag, hare…); it shows on their spell card and on the TV.'),
    ('table', ['Spell', 'Mana', 'Roll', 'Does'], [
        ['Wingardium Leviosa', '2', 'd20 + INT check', 'Levitates an object'],
        ['Accio', '3', 'd20 + INT check', 'Summons a named object'],
        ['Reparo', '1', 'none', 'Mends something broken'],
        ['Aguamenti', '2', 'none', 'Water; puts out fires'],
        ['Finite Incantatem', '2', 'd20 + WIS check', 'Ends a spell or curse'],
        ['Episkey', '3', 'd6', 'Heals that much (you apply it)'],
        ['Flipendo', '2', 'd20 + INT, then d6', 'Knockback damage'],
        ['Rictusempra', '2', 'd20 + CHA to hit', 'Target loses its next turn laughing'],
        ['Diffindo', '3', 'd20 + DEX, then d6', 'Cuts; damage'],
        ['Riddikulus', '3', 'd20 + CHA, then d10', 'Damage, but only to Boggarts'],
        ['Silencio', '3', 'd20 + CHA to hit', 'Target can’t cast next turn'],
        ['Glacius', '4', 'd20 + INT, then d8', 'Freezing damage'],
        ['Confundo', '4', 'd20 + CHA to hit', 'Target attacks the wrong person (you decide)'],
        ['Immobulus', '4', 'd20 + WIS to hit', 'Frozen in place for a round'],
        ['Petrificus Totalus', '5', 'd20 + INT to hit', 'Target skips its next turn'],
        ['Bombarda', '7', 'd20 + INT, then 2d8', 'Explosive damage (advanced)'],
        ['Expecto Patronum', '8', 'd20 + WIS, then d12', 'Drives back dark creatures (advanced, Year 3)'],
    ], [40, 12, 40, 78]),
    ('p', '<b>Custom spells:</b> at the bottom of the Spells tab, give it a name, icon, mana, type (attack with damage, attack with an effect, check, roll, or no roll), stat and dice. It works exactly like a library spell. Effects like “skips a turn” are yours to apply.'),
    ('h3', 'Monsters'),
    ('table', ['Monster', 'HP', 'Defence', 'Attack', 'XP', 'Notes'], [
        ['Cornish Pixie', '4', '12', '+3, d4', '5', 'Come in swarms'],
        ['Devil’s Snare', '14', '10', '+4, d6', '15', 'Hates light and fire'],
        ['Boggart', '10', '12', '+3, d6', '20', 'Laughter hurts it'],
        ['Dueling Club rival', '14', '12', '+3, d6', '15', 'For duels'],
        ['Paint Wraith', '12', '13', '+4, d6', '25', 'Vale’s servant. Fire burns it'],
        ['Acromantula', '22', '13', '+5, d8', '40', 'Forbidden Forest'],
        ['Mountain Troll', '30', '11', '+6, d10', '50', 'Slow, hits like a wall'],
        ['Ashgrove (possessed)', '45', '14', '+5, d8+2', '100', 'Boss, phase 1'],
        ['Corvin Vale', '60', '15', '+6, d10+2', '200', 'Boss, phase 2'],
    ], [38, 12, 18, 24, 14, 64]),

    ('h2', 'Mimics'),
    ('p', 'Place them from the Table tab: <b>Place on this map</b>, then <b>Mimics</b>. The players can never tell a mimic from the real thing until it springs.'),
    ('table', ['Mimic', 'Disguise', 'Stats', 'Its trick'], [
        ['The Hungry Trunk', 'An ordinary Locked chest', '30 HP, Defence 13, +5, d8, 60 XP',
         'Every bite swallows a random item from the target’s bag. Each item: it grows bigger and gains 5 max HP. Potions it swallows heal it. With 3 or more items inside, its bite adds 1d6. When beaten, it spits everything out on the floor, plus its hoard of Galleons.'],
        ['The Painted Double', 'Any person you choose', '26 HP, Defence 14, +4, d6, 60 XP',
         'On its turn it casts the last spell that hit it back at whoever cast it, for the same damage. Incendio does double damage to it: fire burns paint.'],
    ], [30, 32, 34, 74]),
    ('list', [
        '<b>The Hungry Trunk springs itself</b> the moment anyone tries to open it.',
        'If you made your own jump scare video (<i>public/video/jumpscare.mp4</i>), it plays on the TV instead of the drawn maw. Phones still buzz and flash red.',
        '<b>The Painted Double waits for you.</b> When a player talks to it or touches it, select it and press <b>😱 Spring the mimic</b>.',
        'The TV goes black, a monster maw lunges out with a scream, every phone buzzes and flashes red, and a fight starts with the mimic acting first. A Sinclair still goes first: they cannot be surprised.',
        'Selecting a sprung mimic on the GM screen shows what it has swallowed, and who the Double will mirror next.',
        'Story items (the serpent key, the map half, diary pages, ring clues) can never be swallowed.',
    ]),
    ('read', 'The lid creaks. For a moment there is nothing but dark inside. Then the dark has teeth.'),
    ('read', 'Professor Flitwick smiles up at you. It is a perfectly ordinary smile, until it keeps going, wider and wider, past his ears, and his face runs like wet paint.'),
    ('tip', 'One mimic per play day is plenty. Good spots: the Trophy Room during detention, a chest in the Restricted Section, the Double as Prefect Sinclair after she is drained (cruel, and unforgettable), or the Double as a ghost in Hogsmeade. Throwing a Chocolate Frog or Pumpkin Pasty at the Trunk is a clever distraction: let it skip a turn eating.'),
    ('h2', 'House points'),
    ('gm', 'Header: <b>⏳ Points</b>. Type a reason (optional), then tap −10, −5, +5 or +10 beside a student. The TV announces it with the reason.'),
    ('table', ['Award', 'For'], [
        ['+5', 'Good roleplay, a clever idea, kindness, helping another house'],
        ['+10', 'Solving a puzzle, a brave rescue, a brilliant plan, passing a hard lesson first time'],
        ['−5', 'Cheek to a teacher, breaking a small rule, getting caught somewhere silly'],
        ['−10', 'Being caught by Filch after curfew (the wheel does this for you), fighting in corridors'],
    ], [20, 150]),
    ('tip', 'House points are the easiest way to reward players for the things you want more of. Give them out often and say why out loud.'),

    ('h2', 'Wheels'),
    ('gm', 'Wheels tab: choose a wheel and who is spinning, press <b>Spin</b>. It spins on the TV and its result applies to that student when it lands. <b>Re-spin (Felix)</b> is for Felix Felicis.'),
    ('table', ['Wheel', 'Use it when'], [
        ['Bertie Bott’s Beans', 'Someone eats the beans (it spins by itself)'],
        ['Potion brewing', 'Brewing outside class, or as drama during Potions'],
        ['Out after curfew', 'Anyone moving around during Curfew. Filch means −10 points and detention'],
        ['Wand misfire', 'The wrong wand at Ollivanders, or a cursed moment'],
        ['Portrait gossip', 'The Blackwood breaks a rule near a portrait (their drawback)'],
        ['They heard you hiss', 'Someone hears the Marlowe speak Parseltongue (their drawback)'],
        ['Forbidden Forest', 'Each time the party moves through the forest'],
        ['Hogwarts surprises', 'Whenever the table goes quiet'],
        ['Did anyone see?', 'After the Killing Curse (it spins by itself, without naming the caster)'],
    ], [42, 128]),

    ('h2', 'Chests, items and hazards'),
    ('p', 'Place them from the Table tab: <b>Place on this map</b>, then Chests, Items or Hazards. They land on the current map. Tap one and tap the map to move it.'),
    ('table', ['Chest', 'Lock', 'Holds'], [
        ['Small chest', 'DEX 8', '3 to 10 Galleons and a sweet or potion'],
        ['Locked chest', 'DEX 13', '10 to 25 Galleons and two potions or tricks'],
        ['Ancient chest', 'INT 16', '25 to 60 Galleons and two rare things'],
        ['Cursed chest', 'DEX 14', '20 to 40 Galleons and something rare. Failing costs 4 HP'],
    ], [32, 22, 116]),
    ('p', 'Players open chests from the <b>Here</b> tab on their phones. Each student gets one try per chest, so a failure means someone else has to try. Alohomora gives advantage. Selecting a chest on the GM screen shows its loot.'),
    ('p', 'Items on the ground glint on the map. The first student in the room to tap <b>Pick up</b> gets it. This is how you hide clues, diary pages and ring clues.'),
    ('table', ['Hazard', 'When triggered'], [
        ['Shelf of paint jars', 'Destroys every Paint Wraith here and burns bosses for 5'],
        ['Cracked mirror', 'Reflected magic hits bosses for 8'],
        ['Cold braziers', 'Heals every student here by 5'],
        ['Ritual circle', 'Bosses here lose 3 Defence'],
        ['Vale’s empty canvas', '15 damage to bosses'],
        ['Cracked pillar', '6 damage to every enemy here'],
    ], [42, 128]),
    ('p', 'Hazards show on the TV under “Here” as things the players could do. When they choose one, tap it on the GM screen and press its action. Ask for a check first if it should be hard.'),

    ('h2', 'The six families'),
    ('table', ['Family', 'Gift (always)', 'Once a day', 'Drawback'], [
        ['Blackwood', 'Portraits speak freely', 'A portrait must answer one question truthfully', 'Portraits gossip (spin Portrait gossip)'],
        ['Sinclair', 'Can’t be surprised; knows Stupefy', 'Re-roll a d20 in a fight', 'Needs a WIS check to walk away from insults'],
        ['Fenwick', 'Knows the Marauders’ words; has half the map', 'See who is in one area of the castle', 'The missing half (The Other Half)'],
        ['Thornbury', 'Creatures never attack first; advantage to calm them', 'A creature tells what it has seen', 'Will risk anything for a creature'],
        ['Quill', 'Sees through disguises and illusions', 'Ask: what here is hidden or enchanted?', 'Unwanted visions'],
        ['Marlowe', 'Parseltongue; serpent doors open; has the serpent key', 'A snake scouts, guards or carries a message', 'People fear it (spin They heard you hiss)'],
    ], [22, 50, 52, 46]),
    ('p', 'When a student taps their ability on the phone, the TV announces it. You decide what they learn. Abilities recharge each morning.'),

    ('h2', 'Sound, music and the main event'),
    ('list', [
        '<b>Sound effects</b> play on the TV by themselves: spells, hits, natural 20s, house points, level-ups, the wheel ticking, chests, page turns, the clock bell at dawn.',
        '<b>Music:</b> pick a track from the 🎵 menu in the GM header. It loops on the TV and fades between tracks. Suggested: Diagon Alley for the prologue, Great Hall for feasts, Mystery for free time, Forbidden Forest outdoors, Battle for fights, Undercroft for the finale, Victory for the House Cup.',
        '<b>Main event:</b> every phone locks with “Main Event: pay attention to the screen” during the opening, puzzles, the suspect board, awards and the House Cup. Press <b>🎬 Main event</b> to lock them for any big moment yourself, and again to release.',
    ]),
    ('tip', 'Use the main event lock for every story beat. A locked phone is the clearest possible signal that something important is happening.'),
    ('h2', 'Owl Post'),
    ('p', 'A private letter from you to one player. Use it for anything secret: a family secret coming true, a vision, a portrait’s honest answer, a whisper from the painting.'),
    ('gm', '<b>🦉 Owl Post</b> tab: pick the student, choose who it is from (or type anyone), write the letter, press <b>Send</b>. Templates fill in common secrets. The sent list shows whether it has been opened.'),
    ('list', [
        'Their phone: an owl swoops in and drops a sealed letter. They tap the wax seal to read it. It stays in <b>Owl Post</b> on their Sheet.',
        'The TV only says “An owl swoops in with a sealed letter for Zibby…”. Everyone knows a secret happened. Nobody knows what.',
        'Only that player can read it. The database itself enforces this, so even a curious friend with the site open cannot peek.',
    ]),
    ('tip', 'Owls are perfect for the Quill’s visions, the Blackwood’s portrait questions, Vale’s whispers from Day 5 on, and one cruel letter to the Sinclair after the cliffhanger: “It was the painting. It took my colour. Find it. Love, your sister.”'),
    ('h2', 'Levels'),
    ('p', 'Each year has its own level range: <b>Year 1 is levels 1 to 5</b>, Year 2 is 5 to 10, and so on to Year 7. XP stops at the top of the year’s range. Every new level gives <b>+4 max HP and +2 max mana</b> automatically. Give a stat point by hand if you like (Players tab, Edit stats and limits).'),
    ('table', ['Level', '1', '2', '3', '4', '5'], [['XP needed', '0', '100', '250', '450', '700']], [30, 28, 28, 28, 28, 28]),
    ('p', 'XP comes from classes (10 each), fights (shared monster XP), quests and the XP buttons on each card.'),
    ('h2', 'Special rules'),
    ('h3', 'Detention'),
    ('p', 'Players tab: <b>🔦 Detention</b>, or Filch on the curfew wheel. The student is moved to the Trophy Room with Filch, and <b>The Old Cup</b> quietly appears on their phone. Make it fun: Filch makes them polish the trophies, which is exactly how they find the engraving.'),
    ('read', '“Polish them,” Filch growls, dumping a rag and a tin of something foul in front of you. “All of them. By hand. And if I find a single fingerprint, you’re back here tomorrow.” He shuffles out, muttering. You are alone with three hundred years of cups and shields.'),
    ('h3', 'The Killing Curse'),
    ('p', 'Teach it from Players tab, <b>Edit stats and limits</b>, <b>Teach the Killing Curse (secret)</b>. Only one character can ever learn it. They automatically get an owl from the painting telling them they have it, and that Vale will be watching through their eyes. Nothing appears on the TV.'),
    ('h3', 'Expulsion'),
    ('p', 'Only the Killing Curse can get a student expelled, through the secret wheel. An expelled student cannot attend classes. You can reinstate them from Players tab, <b>Edit stats and limits</b>, if the story earns it.'),
    ('h3', 'The Time-Turner'),
    ('p', 'Found through <b>The Turning Lock</b>. When the players use it, press <b>⌛ Use the Time-Turner</b> on the Day &amp; class tab. Everyone returns to Day 1 morning keeping all XP, spells and items. Then it cracks forever.'),
    ('read', 'The tiny hourglass spins in your hand, faster and faster, and the world spins with it: days unwinding, candles un-burning, the grey drained faces of your friends filling back with colour. Then it is morning. Day one. The bell for breakfast is ringing. The Time-Turner gives a small, sad crack, and goes still.'),
]
