BLOCKS = [
    ('chapter', 'Before you begin', 'How to use this book',
     'Everything you need to run The Hollow Heir, in the order you will need it.'),
    ('p', 'This book follows the night from the first owl to the House Cup. Read it once before the first session, '
          'then keep it open beside the GM screen. You never have to read everything out: the boxes tell you what is for the players and what is just for you.'),
    ('h3', 'The four kinds of box'),
    ('read', 'Parchment boxes are read aloud. Read them as written, or in your own words once you know them. They set the scene.'),
    ('wait', 'Red boxes mean stop talking. Ask the question, then let the players answer and argue. Silence is fine. Do not rescue them too early.'),
    ('gm', 'Teal boxes tell you exactly what to press in the app, and when.'),
    ('tip', 'Gold boxes are optional advice. Use them if the moment needs a push.'),
    ('h3', 'Three rules for the table'),
    ('list', [
        '<b>The TV is the table.</b> The players look at the TV, decide together and tell you what they do. You do it for them on the GM screen. Phones are for their own sheet, dice, bag and classes.',
        '<b>Say “yes, and…”</b> If an idea is clever and fits the world, let it work, maybe with a roll. A good idea deserves house points.',
        '<b>The clock is the villain.</b> Every block that passes brings the ritual closer. When the players dither, remind them what time it is.',
    ]),
    ('h3', 'Words you will see'),
    ('table', ['Word', 'Meaning'], [
        ['Block', 'One part of a day: Morning class, Lunch, Afternoon class, Free time, Curfew.'],
        ['Check', 'A d20 roll plus a stat bonus against a difficulty (DC). Meet or beat it to succeed.'],
        ['Defence', 'How hard a character is to hit. Enemies must roll this or higher.'],
        ['Beat', 'A story moment that happens at a set time, whatever the players are doing.'],
        ['Token', 'Anything on the map: students, staff, monsters, chests, items, hazards.'],
    ], [30, 140]),

    ('chapter', 'Before you begin', 'Setting up the night', 'Twenty minutes before anyone arrives.'),
    ('h2', 'The checklist'),
    ('list', [
        'Open the site on your laptop and sign in. From the DM dashboard, press <b>Create game</b> on The Hollow Heir.',
        'Press <b>Open GM screen</b> (your display) and <b>Open TV screen</b> (drag that window to the TV and make it full screen).',
        'The TV shows a four-letter join code. Players sign in on their phones and type it in. Their names pop up on the TV.',
        '<b>Click the TV window once</b> (the gold “Click to enable sound” button). Browsers block sound until someone clicks.',
        'Press <b>Start game</b> when everyone is in. The opening cutscene starts on the TV and every phone locks.',
        'Keep the GM screen open all night. It is the engine that carries out trades, purchases, attacks and chests.',
        'Physical props: the six wands (holly, yew, vine, ash, hawthorn, oak), the Hogwarts letters, snacks. Bertie Bott’s Beans if you can find them.',
        'Open the <b>🎞️ Media</b> tab and check the file checklist. Play the intro and the jump scare once to be sure they are the right files. Missing files fall back to the built-in versions, so it is never a disaster.',
    ]),
    ('gm', 'Header controls: <b>🎵 music</b> picker and volume, <b>🎬 Main event</b> (locks every phone), <b>⏳ Points</b>, the shop switch and the join code. The GM screen has tabs: <b>Table</b> (map, moving people, placing things, fights), <b>Day &amp; class</b>, '
           '<b>Quests</b>, <b>Puzzles</b>, <b>TV shows</b>, <b>Players</b>, <b>Wheels</b>.'),
    ('h2', 'Pacing: how long it really is'),
    ('p', 'Played in full, The Hollow Heir runs <b>14 to 18 hours</b>. The prologue and Sorting take about two and a half hours on their own (Ollivanders and the Sorting Hat are about five minutes per player each), and each in-game day takes one and a half to two hours. Plan for three sessions.'),
    ('table', ['Session', 'Covers', 'Ends on', 'Time'], [
        ['One', 'Opening cutscene, letters, Gringotts, Diagon Alley, Ollivanders, the Express, Sorting, Feast, Days 1 and 2', 'The Sinclair prefect drained (Day 2, Curfew)', '5 hrs'],
        ['Two', 'Days 3, 4 and 5: the library, the missing page, Flying, Alohomora, the Room of Requirement', 'Grimsby caught over a victim (Day 5, Curfew)', '5 hrs'],
        ['Three', 'Hogsmeade (Day 6), Day 7, the Trials, the Undercroft, the finale', 'Awards, the House Cup, saving characters', '5 hrs'],
    ], [18, 82, 50, 20]),
    ('p', 'Every session ends on a cliffhanger beat, and each one starts with a recap: ask the players to tell you the story so far.'),
    ('h3', 'If you only have two sessions'),
    ('p', 'Cut, don’t rush. In this order:'),
    ('list', [
        '<b>Teach some classes without a minigame</b> (Day &amp; class tab). Keep the minigames for Charms, Defence and Flying; they are the most fun.',
        '<b>Shorten the prologue:</b> two Ollivanders questions per player instead of five (just read the first two, then press Give this wand), and shop for ten minutes, not twenty.',
        '<b>Merge free blocks:</b> on Days 3 and 4, treat Lunch and Free time as one block. Press Advance time twice.',
        '<b>Drop side quests</b> nobody has picked up. Keep Wake the Sleepers and The Other Half; they feed the main story.',
        '<b>Skip the Trials</b> and use the Marlowe serpent key into the Undercroft.',
    ]),
    ('p', '<b>Never cut the beats.</b> They are the story.'),
    ('tip', 'Watch the clock, not the plan. If the table is having the time of its life in Hogsmeade, let it run and cut something quieter later.'),

    ('chapter', 'Part 1', 'The Prologue', 'From the opening credits to the Sorting Hat.'),
    ('h2', '1.0 The opening cutscene'),
    ('p', 'When you press <b>Start game</b>, the TV plays the opening. Every phone shows <b>Main Event: pay attention to the screen</b> and cannot be tapped. Dim the lights.'),
    ('list', [
        '<b>Your intro video</b>, if you made one (<i>public/video/intro.mp4</i>). When it ends, the book appears by itself.',
        'Otherwise the built-in opening: <b>the studio ident</b> (about 8 seconds: clouds part around a golden GM crest, then your name and “presents”) and <b>the title</b> (about 8 seconds: <i>Harry Potter and the Hollow Heir</i> in gold, with rising embers).',
        '<b>The storybook:</b> a red leather book appears, closed. You turn the pages from the GM screen.',
    ]),
    ('gm', 'A <b>🎬 Opening cutscene</b> panel sits at the top of the GM screen. Press <b>Open the book</b>, then <b>Next page</b> after each page. The panel shows the words for each page so you can read them aloud (or they play by themselves if you recorded them). After page 6, press <b>Turn to “Choose your family”</b>.'),
    ('read', [
        '<b>Page 1.</b> Three hundred years ago, a painter named Corvin Vale made portraits so lifelike that people swore his subjects breathed.',
        '<b>Page 2.</b> He feared one thing above all others: growing old. So he began his greatest work, a portrait of himself that would never age, never fade, and never end.',
        '<b>Page 3.</b> To finish it, he needed the light of the young. Students began to be found at dawn, grey and silent, as if someone had painted them in ash.',
        '<b>Page 4.</b> A family called Blackwood stopped him. They sealed Vale inside his own unfinished canvas, and hid it where no one would ever think to look.',
        '<b>Page 5.</b> For three centuries, the painting slept. Until this summer, when someone found it, wrapped it in grey cloth, and put it on a train to Hogwarts.',
        '<b>Page 6.</b> Six families are about to receive a letter. Six children are about to begin their first year. None of them know that the painting is waiting for them.',
    ]),
    ('tip', 'Read slowly. Pause after each page before turning. The page turn has its own sound; let it land. If you made your own intro video, wait for it to finish before pressing Open the book.'),
    ('p', 'On the family page, the six families appear in the book and the phones unlock. As each player claims a family, the book stamps their first name onto that family’s card.'),
    ('wait', '“Look at your phones. You were born into one of six families. Read them, argue about them, and choose. Then give yourself a first name.” Give them five minutes.'),
    ('gm', 'When everyone has chosen, press <b>Close the book and begin</b>. The book closes, the phones stay locked for a moment, then the game begins. Go straight to the family vignettes below.'),
    ('h2', '1.1 Letters arrive'),
    ('gm', 'The clock starts at <b>Prologue: Letters arrive</b>. On the Table tab, choose <b>Home</b> and press <b>Just show on TV</b>.'),
    ('read', [
        'Somewhere in Britain, on an ordinary morning at the end of summer, an owl lands where no owl should be.',
        'It is carrying a heavy envelope of yellowish parchment, addressed in emerald-green ink. The seal is a coat of arms: a lion, an eagle, a badger and a snake, around a large letter H.',
        'You are eleven years old. In about a minute, everything you thought you knew about your life is going to change.',
    ]),
    ('p', 'If you skipped the cutscene, players choose their families now on their phones. Otherwise they already have.'),
    ('p', 'Go round the table. Read the family’s vignette, then hand that player their physical letter.'),
    ('h3', 'Blackwood'),
    ('read', 'The letter arrives on a silver tray, carried by a butler-elf who bows so low his nose touches the carpet. Above the fireplace, three generations of painted Blackwoods lean out of their frames to read over your shoulder. “About time,” sniffs your great-great-grandmother. “We were starting to think you were a Squib.”'),
    ('h3', 'Sinclair'),
    ('read', 'Your parents are away again, hunting someone dangerous for the Ministry. The owl finds you alone at the kitchen table. Tucked inside your letter is a second note in your sister’s handwriting: “See you at school. Keep your eyes open this year. Something feels wrong. Don’t tell Mum.”'),
    ('h3', 'Fenwick'),
    ('read', 'The owl crashes straight through the window of Fenwick’s Fizzing Follies and lands in a crate of Dungbombs. When you finally open the letter, it explodes into green confetti. Your family cheers. Later, alone, you open the drawer you are not supposed to open, and unfold the half of a faded old map that lives there.'),
    ('h3', 'Thornbury'),
    ('read', 'The owl lands on the gate of the hippogriff paddock, and the whole herd bows to it. You read the letter sitting on the fence beside an empty stall. The nameplate on the stall still says Bramble. Your family stopped talking about her months ago. You never stopped listening for her.'),
    ('h3', 'Quill'),
    ('read', 'The first letter comes through the letterbox. Your dad throws it away. The next morning there are twelve. By the weekend there are hundreds, and a tall witch in a pointed hat is standing on your doorstep politely asking your parents, both dentists, if she might come in. “You’re a witch,” she tells you. “Or a wizard. Either way, you’re late.”'),
    ('h3', 'Marlowe'),
    ('read', 'The owl finds you in a cold, dusty manor where half the rooms are shut and the portraits have all been turned to face the wall. Nobody has written to a Marlowe in years. Your grandfather reads the letter twice, then presses an old iron key into your hand. It is carved like a serpent. “Keep it hidden,” he says. “Some doors remember our name.”'),
    ('wait', 'For each player: “Tell us one thing about you that nobody at Hogwarts knows yet.” Their answers are gold for later. Write them down.'),
    ('gm', 'If someone says they already know a spell, teach it on the <b>✨ Spells</b> tab: pick the student, tap <b>Teach</b>, and leave <b>Announce on the TV</b> off so it stays their secret. Not in the list? Use <b>Make a custom spell</b> at the bottom.'),
    ('tip', 'Keep backstory spells small: Reparo, Wingardium Leviosa, Episkey, Aguamenti. A first-year who already knows Bombarda breaks the week. If they ask for something big, say yes with a cost: it works once, or it drains them.'),
    ('tip', 'Each player can read their <b>family secret</b> on their own phone (Sheet tab). Remind them it is secret. They can share it whenever they like, or never.'),

    ('h2', '1.2 Gringotts'),
    ('gm', 'Day &amp; class tab: <b>Advance time</b> to <b>Gringotts and Diagon Alley</b>. Table tab: choose <b>Gringotts</b>, tick everyone, <b>Move them here</b>.'),
    ('read', 'Diagon Alley swallows you whole: cauldrons stacked outside shops, owls hooting in cages, a witch selling eyeballs by the jar. At the top of the street stands a snowy-white building with bronze doors. Gringotts Wizarding Bank. A goblin in scarlet and gold looks you up and down as if pricing you. “Vault keys,” he says. “Or account names. Quickly.”'),
    ('p', 'Do the vaults one at a time. It is a great moment to show who is rich and who is not.'),
    ('gm', 'Players tab: on each card press <b>🏦 Open the [family] vault</b>. The TV announces the amount.'),
    ('table', ['Family', 'Vault', 'Say this as the door opens'], [
        ['Blackwood', '500 Galleons', '“Mountains of gold. The goblin almost smiles.”'],
        ['Sinclair', '300 Galleons', '“Neat stacks of gold, and a note from your parents: Spend wisely.”'],
        ['Fenwick', '220 Galleons', '“Gold, a few joke-shop IOUs, and something that fizzes.”'],
        ['Thornbury', '150 Galleons', '“A modest pile of gold, and a hippogriff feather someone left for luck.”'],
        ['Quill', '60 Galleons', '“The Hogwarts fund for Muggle-born students. Enough, if you are careful.”'],
        ['Marlowe', '25 Galleons', '“A handful of coins. The goblin glances at the serpent key in your pocket, and says nothing.”'],
    ], [26, 26, 118]),

    ('h2', '1.3 Diagon Alley'),
    ('gm', 'Header: press <b>🛍️ Open shops</b>. Table tab: move everyone to <b>Diagon Alley</b>.'),
    ('read', 'You have a list from Hogwarts and a pocket full of gold that looks like a pirate’s treasure. Every shop window wants you. Madam Malkin’s robes. The Magical Menagerie, where something in the back is purring very loudly. Flourish and Blotts, stacked to the ceiling with books. And at the far end, a narrow, dusty shop with a single wand on a faded cushion in the window.'),
    ('p', 'On their phones, the <b>Shop</b> tab now has a school list that ticks itself off. Every student needs robes, a familiar, a cauldron and a book set. The wand comes from Ollivanders, which you run.'),
    ('wait', '“You have about fifteen minutes before Ollivanders closes. What do you buy? Who is helping who?” The cheapest full school list costs 20 Galleons, so the Marlowe can only just afford it. Watch whether anyone shares.'),
    ('tip', 'Generosity deserves a reward. If a rich student pays for someone else, give the giver <b>+5 house points</b> once they are sorted, or remember it for the feast.'),
    ('h3', 'The rival'),
    ('read', 'Outside the Menagerie, an older boy in expensive robes is leaning against the wall, tossing a Galleon. He looks at you like you are something on his shoe. “First-years,” he drawls. “Lovely. Try not to cry in the Great Hall this year.” He pockets the coin and strolls off. Someone nearby mutters his name: Cassius Thorne.'),

    ('h2', '1.4 Ollivanders'),
    ('read', 'A bell tinkles somewhere deep in the shop. The place smells of dust and old wood. Thousands of narrow boxes are piled to the ceiling. Then an old man with wide, pale eyes is simply there, as if he has been standing behind the counter all along. “Ah,” he says softly. “I wondered when I would be seeing you.”'),
    ('p', 'Do one student at a time while the others watch. This is the moment the physical wands come out.'),
    ('gm', 'Players tab: on a student’s card press <b>🪄 Wand questions</b>. Their phone and the TV show five questions. Read each question aloud as it appears, in Ollivander’s voice. When they finish, a GM panel suggests the wood and core. Press <b>Give this wand</b>.'),
    ('tip', 'For comedy, before the real wand, hand them a wrong one and spin the <b>Wand misfire</b> wheel for them (Wheels tab). Then: “No, no. Not that one.”'),
    ('read', '“Curious,” Ollivander murmurs, as the wand warms in your hand and a ribbon of light curls from its tip. “Very curious. The wand chooses the wizard, you see. It is not always clear why. But I think we can expect great things from you. Or terrible ones. Often it is the same thing.”'),
    ('table', ['Wood', 'Bonus', 'Physical wand to hand over'], [
        ['Holly', '+1 WIS', 'The holly wand'], ['Yew', '+1 CHA', 'The yew wand'], ['Vine', '+1 INT', 'The vine wand'],
        ['Ash', '+1 CON', 'The ash wand'], ['Hawthorn', '+1 DEX', 'The hawthorn wand'], ['Oak', '+1 STR', 'The oak wand'],
    ], [30, 30, 110]),
    ('p', 'The core adds the rest: <b>phoenix feather</b> +1 spell damage and +2 max mana, <b>dragon heartstring</b> +2 spell damage, <b>unicorn hair</b> +4 max mana. The first wand costs 7 Galleons.'),
    ('gm', 'When everyone has a wand, press <b>🛍️ Close shops</b>.'),

    ('h2', '1.5 Platform Nine and Three-Quarters'),
    ('gm', 'Advance time to <b>The Hogwarts Express</b>. Move everyone to <b>Platform Nine and Three-Quarters</b>.'),
    ('read', 'King’s Cross station, eleven o’clock, and there is no platform nine and three-quarters. There is platform nine. There is platform ten. Between them is a solid brick barrier, and a family with an owl cage has just walked straight into it and vanished.'),
    ('wait', '“How do you get through?” Let them work it out. The Quill has no idea. Whoever explains it to the Quill earns the first kindness of the campaign.'),
    ('read', 'You run at the wall. You do not hit it. Steam rolls over you, and through it you see a scarlet steam engine and a sign: Hogwarts Express, 11 o’clock. Students are hugging their families goodbye. Owls are screeching. A cat is escaping. You have arrived.'),

    ('h2', '1.6 The Hogwarts Express'),
    ('gm', 'Move everyone to <b>The Hogwarts Express</b>. If you like, place the <b>covered painting</b> (People) in a corner of the map, and <b>Prefect Sinclair</b> in the corridor.'),
    ('read', 'The train pulls out of the station and the city falls away into green hills. You have a compartment to yourselves. Somewhere down the corridor, a trolley is rattling closer, and a voice is calling, “Anything from the trolley, dears?”'),
    ('p', 'Let them explore. The TV shows what they can do here: buy from the trolley, explore the carriages, peek at the covered painting.'),
    ('list', [
        '<b>The trolley:</b> anyone with Galleons can buy a Chocolate Frog or Bertie Bott’s Beans. Use Players tab, <b>Give item</b>, and take the gold with the −5 button. Eating the beans spins the bean wheel on the TV by itself.',
        '<b>Prefect Sinclair</b> checks on her younger sibling and introduces herself to everyone. She is brisk, kind and clearly tired. If the Sinclair player talks to her privately, she admits she has been having bad dreams about paintings.',
        '<b>Cassius Thorne</b> passes the compartment and makes a point of greeting the Marlowe by surname, loudly.',
    ]),
    ('h3', 'The covered painting'),
    ('read', 'In the last carriage, between the luggage racks, something large leans against the wall, wrapped in grey cloth and tied with cord. A painting, by the shape of it. There is no label. The cold in that carriage is the kind you feel in your teeth.'),
    ('p', 'If the Quill goes near it, read this to them alone, or say it quietly to the whole table:'),
    ('read', 'The cloth has slipped at one corner. Through the gap, you see a painted eye. It blinks. It follows you as you step back. When you look again, the cloth is in place, as if it never moved.'),
    ('wait', '“What do you do?” Nobody else saw it. The Quill can tell the others, or keep it to themselves.'),

    ('h2', '1.7 The Sorting'),
    ('gm', 'Advance time to <b>The Welcome Feast</b>. Move everyone to <b>The Great Hall</b>.'),
    ('read', [
        'The boats cross a black lake under a sky full of stars, and Hogwarts rises above you, every window lit. Inside, you are led into a hall so tall that its ceiling is the night sky itself. Thousands of candles float in the air. Four long tables full of students fall silent.',
        'On a stool at the front sits a battered, patched old hat. A rip near its brim opens like a mouth, and it begins to sing.',
    ]),
    ('read', [
        '“Put me on and let me look / beneath the face you show the room. / The brave of heart to red and gold, / the loyal to the badger’s home, /',
        'the sharp of mind to blue and bronze, / the hungry-hearted, green and silver. / And if you think you know your place, / I promise you: I’ll know it better.”',
    ]),
    ('p', 'Call the students up one at a time, in alphabetical order by family name: Blackwood, Fenwick, Marlowe, Quill, Sinclair, Thornbury.'),
    ('gm', 'Players tab: press <b>🎩 Sorting Hat</b> on that student’s card. Read each question aloud in the Hat’s voice as it appears on the TV. The last question asks if they want a particular house: if their wish is close to their best score, the Hat listens. Press the highlighted house to confirm, or choose another.'),
    ('tip', 'Give the Hat personality. Before the verdict, mutter something about their answers: “Brave, yes, but you chose the runes over the ticking box. Interesting.” The bigger the pause, the bigger the cheer.'),
    ('read', 'The Hat shouts the name of your house, and one of the four tables explodes into applause. You stumble to your seat, your ears still ringing.'),
    ('h3', 'The Welcome Feast'),
    ('read', [
        'Golden plates fill with food out of nowhere: roast potatoes, pies, puddings, things you have never seen before. Ghosts drift through the tables. When the last plate has cleared itself, the Headmaster rises.',
        '“Welcome, all. A few notices. The Forbidden Forest is forbidden: the name was a clue. Curfew is at nine. Mr Filch reminds you that he has keys to every door in this castle, and he is not afraid to use them.',
        '“And this year we have a gift. Professor Ashgrove, our new Defence teacher, has generously added to the castle’s collection of portraits. Do say hello to them. Most of them like to talk.”',
    ]),
    ('p', 'Ashgrove stands and gives a warm wave. Everyone likes him at once. That is the point.'),
    ('gm', 'Table tab: press <b>👩‍🏫 Send all staff to their rooms</b>. Then move each student to their own <b>common room</b> and <b>Advance time</b>. The first school day begins.'),
    ('tip', 'Each common room has its own way in (see the appendix). Make every student do theirs once. It makes the houses feel real.'),
]
