BLOCKS = [
    ('chapter', 'Part 6', 'The Finale', 'The seventh night. Below the castle, a painter is waiting to finish himself.'),
    ('h2', 'Getting in'),
    ('p', 'There are two ways into the Undercroft. Both are fine. The best finales use both, with the party split.'),
    ('list', [
        '<b>The Trials Beneath:</b> Devil’s Snare, the Torch Wall, the Living Chessboard, the Seven Bottles. Only one student can drink the way forward.',
        '<b>The serpent door:</b> the Marlowe turns the serpent key and speaks Parseltongue. It opens straight into the Undercroft. Spin <b>They heard you hiss</b> if anyone is watching.',
    ]),
    ('read', 'The serpent carved on the door uncoils. Its stone scales grind against each other, and the door swings inward on a breath of cold, painted air. Beyond it, a staircase spirals down into green light.'),
    ('h2', 'Setting the stage'),
    ('gm', 'Move everyone who gets through to <b>The Undercroft</b>. Place: <b>Ashgrove (possessed)</b>, two <b>Paint Wraiths</b>, and the hazards <b>Ritual circle</b>, <b>Vale’s empty canvas</b>, <b>Shelf of paint jars</b>, <b>Cracked mirror</b> and <b>Cold braziers</b>. Also place <b>The covered painting</b> (People), now uncovered.'),
    ('read', [
        'The Undercroft is a vast round chamber of serpent-carved pillars. In the centre, a circle of runes has been painted on the floor in something dark. Inside it stands an empty picture frame, taller than a man, its canvas blank and wet.',
        'Around the circle, in a ring, stand the drained students: grey, silent, upright, staring at nothing. A thin silver light flows from each of them into the empty canvas.',
        'And in front of the frame, his back to you, is Professor Ashgrove. He turns. His eyes are brushstrokes. His smile is not his own. “Ah,” says a voice that is not Ashgrove’s. “The audience has arrived.”',
    ]),
    ('wait', '“The TV shows everything in the room. What do you do?” This is the moment to let them plan. Count the hazards with them if they miss them.'),
    ('h2', 'Phase 1: Ashgrove'),
    ('gm', 'Press <b>Start fight</b>. Run it as normal. Paint Wraiths take extra punishment from fire: Incendio, or the paint jars (which destroy every wraith at once).'),
    ('read', '“You were my favourite students,” Ashgrove says, with tears in his painted eyes. “I am so sorry. He is so very strong.” Then his wand rises, and the voice behind his voice laughs.'),
    ('tip', 'Ashgrove is a victim. If anyone tries to talk to the real Ashgrove (CHA 16), give his next attack disadvantage, or let him whisper the canvas is the key.'),
    ('read', 'Ashgrove falls to his knees. The paint drains from his eyes in grey tears, and he collapses, himself again, unconscious. For a heartbeat, the chamber is silent. Then the blank canvas ripples, and a man steps out of it.'),
    ('h2', 'Phase 2: Corvin Vale'),
    ('gm', 'Press <b>End and share XP</b> (Ashgrove’s XP is shared). Place <b>Corvin Vale</b> beside the frame, then press <b>Start fight</b> again. Paint Wraiths still standing join the new fight.'),
    ('read', [
        'He is beautiful in the way a painting is beautiful: too perfect, too still, colours too bright. Velvet the colour of old blood. Hands stained with three centuries of paint.',
        '“Corvin Vale,” he says, bowing. “Painter. I have waited three hundred years for an audience worth finishing in front of. When the last of their light is in my canvas, I will be real again, and I will never, ever end.”',
    ]),
    ('list', [
        '<b>Breaking the ritual circle</b> drops his Defence by 3. Without it, he is very hard to hit.',
        '<b>Burning or slashing the canvas</b> deals 15 to him. Each hit on the canvas makes the drained students flicker with colour.',
        '<b>The cracked mirror</b> reflects a spell for 8. <b>The braziers</b> heal the party for 5.',
        'The <b>Killing Curse</b> hits him for 20 if it lands, and the secret wheel spins. Even here, someone might see.',
    ]),
    ('tip', 'Vale talks during the fight. Use the players’ secrets against them: he knows the Blackwood debt, the Marlowe ancestor, the Quill who saw his eye. A villain who knows your name is far scarier than one with more HP.'),
    ('h2', 'Victory'),
    ('read', [
        'Vale reaches for the canvas, and it tears in his hands. Colour floods out of it like a breaking dam: silver, gold, every shade of every student he took. It pours back into the grey figures around the circle, and one by one they gasp and fall, alive, crying, themselves.',
        'Vale looks down at his hands. They are fading. “Unfinished,” he whispers, almost in wonder. Then there is only an empty frame, and the smell of turpentine, and somewhere far above, the bell for morning.',
    ]),
    ('gm', 'Complete <b>The Hollow Heir</b> and <b>The Trials Beneath</b> on the Quests tab. Give out house points for bravery. Then go to “Ending the night”.'),
    ('h2', 'Defeat'),
    ('p', 'If the last block of Day 7 ends and Vale still stands, or the whole party is knocked out:'),
    ('read', 'The canvas drinks the last of the light. Corvin Vale breathes in, deeply, for the first time in three hundred years, and steps out of the circle on real feet. He walks past you as if you are already a painting. Somewhere above, the portraits begin, very softly, to applaud.'),
    ('p', 'Record a <b>loss</b>. It stings, and that is fine. The players can still win the House Cup, and the awards still happen.'),

    ('chapter', 'Part 7', 'Ending the Night', 'The last fifteen minutes are what they will talk about tomorrow.'),
    ('h2', 'Tonight’s awards'),
    ('gm', 'TV shows tab: <b>🎖️ Tonight’s awards</b>. The TV fills with awards worked out from the whole night: Heaviest Hitter, Unbreakable, Point Machine, Luckiest Wand, Glorious Disaster, Top of the Class, Treasure Hunter, Wand Never Rests.'),
    ('tip', 'Read each one out like an award ceremony. Ask the winner for a one-line speech.'),
    ('h2', 'The House Cup'),
    ('gm', 'TV shows tab: <b>🏆 House Cup ceremony</b>. The winning house takes over the TV with the standings, and the House Cup goes into each winner’s trophy cabinet on their account.'),
    ('read', 'The Great Hall is hung with banners in the winning colours. The Headmaster raises his glass. “A strange year. A frightening one. And at the end of it, students who would not stand by. The House Cup goes to…”'),
    ('wait', 'Pause. Long. Then read the house name. Then let them cheer.'),
    ('h2', 'Record the result and save the characters'),
    ('gm', 'On the DM dashboard, press <b>Record win</b> or <b>Record loss</b>. A win puts the campaign trophy, Saviour of Hogwarts, in every player’s cabinet. Either way, <b>every character is saved to its player’s profile</b>: level, XP, house, stats, spells, wand, robes, familiar, bag and Galleons. There is also a <b>Save characters now</b> button on the Players tab if you want to save at the end of a session.'),
    ('p', 'Players see their character on their dashboard under <b>Your characters</b>, marked “Year 1 complete”. In Year 2, the family picker offers <b>Continue as…</b> and everything comes back. New players joining in Year 2 start at level 5.'),
    ('h2', 'The epilogue and the Year 2 hook'),
    ('read', 'The train pulls out of Hogsmeade station under a bright summer sky. Behind you, the castle grows small. In the last carriage, between the luggage racks, there is nothing at all, just an empty space on the wall where something used to hang. You are fairly sure it is gone. Fairly sure.'),
    ('p', 'Then, after a pause, read the sting. This is what Year 2 grows from.'),
    ('read', [
        'That night, long after the last student has gone home, the Headmaster’s office is dark and quiet. Around the walls, the portraits of every headmaster who ever served Hogwarts are asleep in their frames.',
        'All except one. The frame belongs to a headmaster from three hundred years ago, the one who first welcomed a young painter named Corvin Vale to the castle. The frame is empty.',
        'On the desk below it lies a single sheet of paper, in handwriting nobody living would recognise. It says: <i>One down. Six to go.</i>',
    ]),
    ('wait', 'Say nothing. Let them react. Then: “See you in Year 2.”'),
    ('tip', 'The empty headmaster’s frame, “six to go” (one for each year left), and the fact that Vale was invited: that is enough to build Year 2 on, without promising anything yet.'),

    ('chapter', 'Appendix', 'Quick Reference', 'Voices, entrances, clues, and what changed.'),
    ('h2', 'NPC voices'),
    ('table', ['Character', 'Voice and manner', 'Wants'], [
        ['Professor Ashgrove', 'Warm, encouraging, remembers names. Too warm.', 'To be loved. Now: to be free of Vale.'],
        ['Professor Grimsby', 'Clipped, sarcastic, never looks up. Secretly kind.', 'To wake the victims without anyone noticing.'],
        ['Professor Flitwick', 'Squeaky, excitable, stands on books.', 'A champion for the Dueling Club.'],
        ['Professor Longbottom', 'Gentle, nervous laugh, talks to plants.', 'To save the students. Believes in the Restorative Draught.'],
        ['Professor Scamander', 'Dreamy, distracted, the suitcase thumps.', 'Creatures treated kindly. Bramble home.'],
        ['Professor Vance', 'Crisp and exact. Taps her wand on the desk.', 'Precision. Order. Silence.'],
        ['Madam Hooch', 'Barks like a sports coach. Hates excuses.', 'Nobody falling off a broom.'],
        ['Argus Filch', 'Mutters, shuffles, threatens. Talks to his cat.', 'To catch someone, anyone, after curfew.'],
        ['Peeves', 'Shrieks, rhymes, throws things.', 'Chaos. He stole Grimsby’s ingredients.'],
        ['Prefect Sinclair', 'Brisk, tired, protective of her sibling.', 'For someone to believe her.'],
        ['Cassius Thorne', 'Lazy, smug drawl, flips a Galleon.', 'To win. Holds the other map half.'],
        ['Corvin Vale', 'Velvet-soft, patient, speaks in colours and brushstrokes.', 'To finish his self-portrait and live forever.'],
    ], [36, 76, 58]),
    ('h2', 'Common room entrances'),
    ('table', ['House', 'Where', 'How to get in'], [
        ['Gryffindor', 'Tower, off the Grand Staircase', 'Tell the Fat Lady the password: “Lionheart”.'],
        ['Ravenclaw', 'Tower, off the Grand Staircase', 'Answer the eagle knocker: “The more you share me, the more of me there is. What am I?” (Knowledge.) A wrong answer means waiting for someone cleverer.'],
        ['Hufflepuff', 'Basement, through the Kitchens', 'Tap the barrel two from the bottom, middle of the second row, in the rhythm of “Helga Hufflepuff”. Wrong barrel: a shower of vinegar.'],
        ['Slytherin', 'Dungeons, under the lake', 'Say the password to the bare stone wall: “Silver Tongue”.'],
    ], [26, 46, 98]),
    ('p', 'The Kitchens are behind a painting of a fruit bowl. Tickle the pear and it giggles and turns into a door handle.'),
    ('h2', 'Clues: where they are found'),
    ('table', ['Clue', 'Found', 'Pin under'], [
        ['Grimsby’s store cupboard was raided', 'Day 1, Grimsby’s rant', 'Grimsby'],
        ['Every portrait near an attack had gone silent', 'Day 2, the first victim', 'The covered painting'],
        ['Ashgrove’s classroom has more paintings every day', 'Day 4, any visit to Defence', 'Ashgrove'],
        ['Filch has keys to every corridor', 'Day 4, asking Filch or detention', 'Filch'],
        ['Cassius was seen with half of an old map', 'Day 4, the courtyard', 'Cassius'],
        ['A page about Corvin Vale', 'Day 4, Restricted Section (before Free time)', 'The covered painting'],
        ['The covered painting hangs in a different corridor each night', 'Any night, asking a ghost or portrait', 'The covered painting'],
        ['The covered painting’s eyes follow a Quill', 'Whenever the Quill tells the others', 'The covered painting'],
        ['Grimsby was found standing over the third victim', 'Day 5, Curfew', 'Grimsby'],
        ['Grimsby was secretly brewing a draught (clears)', 'Day 5 onward, his office or the bottle', 'Grimsby'],
        ['Filch was supervising a detention on night two (clears)', 'Detention, or asking around', 'Filch'],
        ['Cassius was in the Hospital Wing on night three (clears)', 'Visiting the Hospital Wing', 'Cassius'],
        ['A ghost saw a figure “step out of a frame”', 'Day 6, the Three Broomsticks or any ghost', 'A Hogwarts ghost'],
        ['Ashgrove’s eyes looked like brushstrokes', 'Day 6, Free time', 'Ashgrove'],
        ['Flecks of wet paint on Ashgrove’s sleeve', 'Day 6, looking closely', 'Ashgrove'],
    ], [74, 60, 36]),
    ('tip', 'Pin a clue under the wrong suspect if that is what the players believe. The board shows their theory, not the truth.'),
    ('h2', 'Items to place before each day'),
    ('table', ['Item', 'Where', 'For'], [
        ['Stolen ingredient jars', 'Grand Staircase (Peeves)', 'Stolen Ingredients'],
        ['Torn page about Corvin Vale', 'Restricted Section, Day 4', 'The main mystery'],
        ['Scratched note (first ring)', 'Trophy Room', 'The Turning Lock'],
        ['Star chart (second ring)', 'Astronomy Tower (or from The Old Cup)', 'The Turning Lock'],
        ['Feathered card (last ring)', 'Owlery', 'The Turning Lock'],
        ['Page of Vale’s diary (×3)', 'Restricted Section, Black Lake, Shrieking Shack', 'The Painter’s Bargain'],
        ['Rare Chocolate Frog card', 'An ancient chest anywhere', 'Card Collector'],
    ], [56, 70, 44]),
    ('h2', 'Media files'),
    ('p', 'Everything below is optional: the app has a built-in fallback for every file. Put files in the project’s <b>public</b> folder with exactly these names, then check them on the GM screen’s <b>🎞️ Media</b> tab, which ticks every file it finds and lets you preview the cutscenes, sounds and music.'),
    ('table', ['What', 'File', 'Notes'], [
        ['Intro video', 'video/intro.mp4', '1920×1080 MP4 (H.264, AAC). Replaces the ident and title. Any length; the book opens when it ends. The current pair runs about 16 seconds.'],
        ['Jump scare video', 'video/jumpscare.mp4', '1920×1080 MP4. Plays for mimics instead of the drawn maw. Keep it short (2 to 4 seconds).'],
        ['Intro music', 'sounds/music/intro.mp3', 'Plays under the opening cutscene.'],
        ['Music tracks', 'sounds/music/&lt;id&gt;.mp3', 'castle, great-hall, diagon, mystery, forest, battle, undercroft, victory. Royalty-free or Creative Commons only.'],
        ['Narration', 'sounds/narration/page-1.mp3 to page-6.mp3', 'Your voice reading each storybook page. Plays as the page turns.'],
        ['Storybook pictures', 'story/page-1.jpg to page-6.jpg', 'About 4:5 portrait. The left-hand page of the book.'],
        ['Portraits', 'portraits/&lt;family&gt;.jpg', 'blackwood, sinclair, fenwick, thornbury, quill, marlowe. Square, face centred (cropped to a circle).'],
        ['Maps', 'maps/&lt;place id&gt;.jpg', 'All 35 places; ids are in public/maps/README.md. Wide 16:9, high overhead view.'],
        ['Puzzle portrait', 'puzzles/portrait.jpg', 'Square. Cut into the 3×3 Scrambled Portrait.'],
    ], [30, 52, 88]),
    ('h2', 'Printing this book'),
    ('list', [
        '<b>Page size:</b> A4 portrait (210 × 297 mm).',
        '<b>Your cover:</b> save it as <i>docs/dm-guide/cover.jpg</i> (or .png) and rebuild. It fills page 1 edge to edge and a title page follows. Design it at 2480 × 3508 pixels (A4 at 300 dpi). If the printer wants bleed, make it 2551 × 3579 pixels (3 mm extra on every side) and keep text 10 mm away from the edges.',
        '<b>Binding:</b> spiral or wire binding lets the book lie flat beside the laptop. Print double-sided.',
        '<b>Colour:</b> the read-aloud boxes are parchment-coloured and the GM boxes teal. Both stay readable in black and white.',
    ]),
    ('h2', 'Version log'),
    ('table', ['Version', 'Date', 'Changes'], [
        ['2.1', 'October 2026', 'The living castle: every person has a place for all 35 blocks of the week and moves there on Advance time, along with the clues, chests, hazards and monsters for that block. Quests on offer, conversations on the GM screen, and the companion Conversation Book.'],
        ['2.0', 'October 2026', 'Final edition for Year 1. Written by Zibby. Custom intro and jump scare videos, the Media tab for testing, the media file list, print notes and support for a designed cover.'],
        ['1.4', 'October 2026', 'Owl Post, yearly levels with level-up bonuses, saved characters carrying into Year 2, a pacing plan (three sessions, what to cut), and the Year 2 hook.'],
        ['1.3', 'October 2026', 'Mimics: The Hungry Trunk and The Painted Double, with a jump scare on the TV and phones.'],
        ['1.2', 'October 2026', 'Spells tab: teach any spell from a library of 25, Patronus forms, custom spells, secret or announced.'],
        ['1.1', 'October 2026', 'Opening cutscene (studio ident, title, storybook with family picking), sound effects, music, and the main event phone lock.'],
        ['1.0', 'October 2026', 'First edition. Matches the app with: families, ceremonies, clock, classes and minigames, map and tokens, fights, wheels, quests and secret quests, nine TV puzzles, suspect board, detention, hazards, awards and the House Cup.'],
    ], [18, 28, 124]),
    ('p', 'When the app changes, update this book in the same step: edit the content files, bump the version, add a line here, and rebuild.'),
]
