def quest(title, when, hook, steps, reward, notes=None):
    out = [('h3', title), ('p', f'<b>When:</b> {when}'), ('read', hook),
           ('list', [f'<b>{i + 1}.</b> {s}' for i, s in enumerate(steps)]),
           ('p', f'<b>Reward:</b> {reward}')]
    if notes:
        out.append(('tip', notes))
    return out


def puzzle(title, where, intro_note, how, hints, answer, fail):
    return [('h2', title), ('p', f'<b>Where and when:</b> {where}'), ('read', intro_note),
            ('p', f'<b>How it plays:</b> {how}'),
            ('table', ['Hint', 'Say this if they are stuck'], [['Gentle', hints[0]], ['Stronger', hints[1]], ['Almost the answer', hints[2]]], [30, 140]),
            ('p', f'<b>Answer:</b> {answer}'), ('p', f'<b>If they fail:</b> {fail}')]


BLOCKS = [
    ('chapter', 'Part 4', 'Quests', 'Eight quests to hand out, and four that stay secret until earned.'),
    ('gm', 'Quests tab: tick who the quest is for and press <b>Give quest</b>. Tick objectives as they happen. <b>Complete</b> hands out the rewards automatically. Secret quests sit under <b>🔒 Secret quests</b> and only appear on phones once you press <b>Reveal to them</b>.'),
    ('h2', 'The main quest'),
    *quest('The Hollow Heir', 'Give it to everyone after the first victim (Day 2, Curfew).',
           'Somebody, or something, is feeding on the students of Hogwarts. The teachers are frightened. The portraits are hiding. If anyone is going to find out what is happening, it is going to be you.',
           ['Find out what is draining the students (the paintings, Day 2 to 4).',
            'Learn the name of the painted man (Corvin Vale: the library page, the Three Broomsticks, the diary).',
            'Find the way into the Undercroft (The Trials Beneath, or the Marlowe key and Parseltongue).',
            'Stop the ritual before the seventh night ends (the finale).'],
           '150 XP each and 50 house points each. Completing it is winning the campaign.'),
    ('h2', 'Side quests'),
    *quest('Keep an Eye Out', 'Day 1, Lunch. Prefect Sinclair, to the Sinclair (and friends).',
           '“I’m probably being silly,” the prefect says, glancing at a portrait over your shoulder. “But the castle feels wrong this year. If you’re out after dinner, meet me by the Grand Staircase. I want to show you something.”',
           ['Meet the prefect after dinner.', 'Follow her patrol route (she shows them a corridor where the portraits have gone quiet).', 'Find what she was afraid of (the covered painting, Day 1 or 2 at Curfew).'],
           '30 XP and 10 house points.', 'The prefect is drained on Day 2. If the players never met her, the cliffhanger hurts less. Push this quest hard on Day 1.'),
    *quest('Stolen Ingredients', 'Day 1, Free time. Professor Grimsby.',
           '“Somebody,” Grimsby hisses, “has been in my store cupboard. Boomslang skin. Lacewing flies. Gone. If I find out it was a first-year, they will be scrubbing cauldrons until they are forty.”',
           ['Search the Dungeons for clues (sticky fingerprints, a dropped jar).', 'Catch the thief (it is Peeves, hoarding them to throw at students).', 'Return the jars to Grimsby.'],
           '30 XP, 10 Galleons and two Pepperup Potions each.', 'Place <b>Stolen ingredient jars</b> as an item somewhere Peeves haunts, like the Grand Staircase. Grimsby being grateful is a seed for clearing him later.'),
    *quest('Dueling Club Champion', 'Day 2, Free time. Professor Flitwick.',
           '“Dueling Club!” squeaks Professor Flitwick, standing on a pile of books. “Every evening in the Great Hall. Fair fights, friendly spells, nobody gets stunned into next week. Well. Rarely.”',
           ['Beat a Dueling Club rival (place a <b>Dueling Club rival</b> and fight).', 'Beat two more rivals.', 'Win the final against an older student (Cassius Thorne, using rival stats).'],
           '40 XP and 15 house points each.'),
    *quest('Wake the Sleepers', 'Day 3, Lunch, after the second victim. Professor Longbottom.',
           '“There’s a draught,” Longbottom says quietly, turning a Mandrake leaf in his fingers. “A Restorative Draught. Old magic. It might bring them back. I’d need Mandrake, and someone with a steady hand at a cauldron.”',
           ['Gather 3 Mandrake leaves (Herbology gives one each; chests and Longbottom can give more).', 'Brew the Restorative Draught (an INT check, or spin Potion brewing).', 'Bring it to the Hospital Wing.'],
           '60 XP, 20 house points and a Wiggenweld Potion each.', 'When they deliver it, give them a <b>Restorative Draught</b> moment: the prefect wakes and whispers one clue: “The man in the painting… he was wearing Ashgrove’s face.”'),
    *quest('Where is Bramble?', 'Day 3, Care of Magical Creatures. Professor Scamander, for the Thornbury.',
           '“A hippogriff has been seen at the edge of the forest,” Scamander says. “Grey. Proud. Torn tag on her leg.” She looks right at the Thornbury. “I believe she might be yours.”',
           ['Find Bramble’s tracks in the Forbidden Forest (spin the forest wheel each visit).', 'Calm Bramble without hurting her (Thornbury has advantage; Creature treats help).', 'Bring her safely out of the forest.'],
           '50 XP, 15 Galleons and Creature treats each.', 'Bramble can return in the finale and carry someone to safety.'),
    *quest('The Other Half', 'Day 4, Lunch, when Cassius is seen with a map. For the Fenwick.',
           'Cassius is lounging on the courtyard wall, unfolding a piece of old parchment. It is torn straight down the middle, and the torn edge is exactly the same shape as the one in your pocket.',
           ['Find out who has the other half (Cassius).', 'Win it back, by trade, trick or duel.', 'Join the halves.'],
           '50 XP and a rare Chocolate Frog card.', 'Once joined, the Fenwick’s ability works anywhere, and the map shows a passage to the Undercroft from the Dungeons.'),
    *quest('Card Collector', 'Any free block. A Ravenclaw collector in the library.',
           'An older Ravenclaw with ink-stained fingers is sorting Chocolate Frog cards into piles. “I’m missing one,” she sighs. “A rare. Find it for me and I’ll tell you something about the painting nobody else knows.”',
           ['Find a rare Chocolate Frog card (in an ancient chest, or from The Other Half).', 'Trade it to the collector.'],
           '25 XP and Felix Felicis.', 'Her secret: “It came with the new portraits. Ashgrove signed for it himself.”'),

    ('h2', 'Secret quests'),
    ('p', 'Only you can see these until you reveal them. Each one is found by curiosity, not given by a teacher.'),
    *quest('The Old Cup', 'Detention in the Trophy Room starts it automatically.',
           'Polishing the oldest cup in the case, you notice tiny letters engraved beneath the names of a forgotten team: “Where the stars are closest, the second ring waits.”',
           ['Read the engraving on the old cup.', 'Follow it to the Astronomy Tower.', 'Find what was hidden there (a ring clue and Felix Felicis).'],
           '30 XP, the second ring clue and Felix Felicis.'),
    *quest('The Turning Lock', 'Reveal it when they find the Room of Requirement (walk past the wall three times, thinking of what they need).',
           'The Room of Requirement opens into a cathedral of forgotten things. Deep inside, on a stone plinth, sits a small iron chest with three stone rings for a lock. From inside comes a faint, steady ticking.',
           ['Find the Room of Requirement.', 'Find the three ring clues (Trophy Room, Astronomy Tower, Owlery).', 'Turn the rings to open the lock (the Turning Lock puzzle).'],
           '60 XP. By hand: the Time-Turner (one use).', 'Place the three ring clue items: <b>Scratched note</b> in the Trophy Room, <b>Star chart</b> on the Astronomy Tower, <b>Feathered card</b> in the Owlery.'),
    *quest('The Trials Beneath', 'Reveal it when they reach the serpent door below the Dungeons.',
           'At the bottom of the forgotten stair stands a door carved with a great stone serpent. Beneath it, cut into the floor, are four words: Brave. Clever. Patient. Wise. The door does not open. Somewhere behind it, something is humming.',
           ['Get past the Devil’s Snare (fight it, or Lumos or Incendio).', 'Light every torch on the Torch Wall.', 'Win the Living Chessboard.', 'Drink from the right bottle (the Seven Bottles).'],
           '120 XP and 40 house points each.', 'There is a second way in: the Marlowe key turned while speaking Parseltongue opens the serpent door directly. Reward either path.'),
    *quest('The Painter’s Bargain', 'Reveal it to one student who goes near the covered painting alone, ideally Day 5 or 6.',
           'In the dark, the painting speaks. Its voice is soft, warm, patient. “You want to protect them. Your friends. I know a curse that cannot be blocked, child. One word, and nothing will ever hurt them again. Prove you deserve it, and it is yours.”',
           ['Find all three pages of Vale’s diary (Restricted Section, Black Lake, Shrieking Shack).',
            'Decode the diary’s runes (the Vale’s Diary puzzle).',
            'Go to the painting alone, during curfew.',
            'Answer the painting’s question truthfully.',
            'Choose: accept the bargain, or walk away.'],
           '50 XP. By hand: the Killing Curse.',
           'Place three <b>Page of Vale’s diary</b> items. The decoded line tells them to come alone. The painting asks: “What would you give up to never lose again?” Any honest answer is accepted. If they accept, teach the curse from Players tab, <b>Edit stats and limits</b>. Nothing is shown on the TV. The price: once a day, Vale can look through that student’s eyes. Tell them privately.'),

    ('chapter', 'Part 5', 'Puzzles', 'On the TV, solved out loud, operated by you.'),
    ('gm', 'Puzzles tab: press <b>Put it on the TV</b>. Phones show “Puzzle on the TV!”. The players tell you what to do and you make the moves. Most puzzles detect when they are solved. The solution hides behind <b>Show the solution (GM only)</b>. <b>Close</b> returns the TV to the map.'),
    ('tip', 'Read the intro on the TV aloud, then step back. Let them argue. Count to sixty before offering the gentle hint. A puzzle solved together is worth +10 house points to each student who helped.'),
    *puzzle('The Living Chessboard', 'The Trials Beneath, third chamber.',
            'You step into a vast dark chamber. Torches flare along the walls, and you see you are standing on a giant chessboard. The black pieces tower over you, carved from stone, with blank faces. A voice echoes: “Take your places. White to move. Checkmate in two.”',
            'Assign each player a white piece (tap a piece, choose their name). They decide moves together. Tap a piece, then its square.',
            ['“The rook is strong, but something is in its way.”', '“What if the bishop moved somewhere it guards the king’s only escape?”', '“The bishop wants to go to e6.”'],
            '1. Bishop d7 to e6 (it clears the rook’s path and guards g8). Whatever Black does, 2. Rook a7 to h7 is checkmate.',
            'Any other first move lets Black escape. A black piece slams down nearby: the student whose piece moved takes d6 damage (adjust HP). Press Reset and try again.'),
    *puzzle('The Torch Wall', 'The Trials Beneath, second chamber. Or anywhere dark.',
            'A wall of twenty-five iron torches, five by five, most of them cold. When you touch one, it flares or dies, and so do the torches directly around it.',
            'They call a torch by row and column; tap it. It flips along with its neighbours above, below, left and right.',
            ['“Work row by row. Fix the top row, then never touch it again.”', '“To light a dark torch in one row, touch the torch directly below it.”', 'Name two of the solution torches from the GM panel.'],
            'Six touches: row 1 col 1, row 1 col 2, row 1 col 5, row 3 col 3, row 4 col 1, row 4 col 5. Any order. Other solutions also work.',
            'There is no failure, only time. If the clock matters, spin Hogwarts surprises while they work.'),
    *puzzle('The Seven Bottles', 'The Trials Beneath, final chamber.',
            'Purple flames leap up behind you. Black flames rise ahead. On a table stand seven bottles in a row, and a scroll of clues. One bottle lets you walk through the black fire. One takes you safely back. Two will put you to sleep. Three are poison.',
            'Clues are on the TV. When a student drinks, tap that bottle to reveal it.',
            ['“The tall bottles. What does clue three tell you?”', '“If the poisons can’t sit side by side, where can they go?”', '“The way back is the tiny one at the end.”'],
            'Bottle 4, the small gold one. Poisons 1, 3, 5. Sleep 2, 6. The way back is 7.',
            'Poison: d6 damage and spin Potion brewing for drama. Sleep: they are out until another student wakes them. Only one student can go forward. That splits the party, which is the point.'),
    *puzzle('The Turning Lock', 'The Room of Requirement, after The Turning Lock quest.',
            'Three stone rings, each carved with six symbols, turn under your fingers with a grinding sound. Above them, a small arrow. Inside the chest, something ticks.',
            'They name a ring and a direction; turn it. It opens when the right three symbols sit under the arrow.',
            ['“Read your three clue notes again, in order.”', '“What sleeps beneath the castle? What is the lamp of the night?”', '“Serpent, then moon. And who carries every letter?”'],
            'Serpent, Moon, Owl.', 'No failure. The ticking just gets louder.'),
    *puzzle('Vale’s Diary', 'After they collect all three diary pages (The Painter’s Bargain).',
            'Three pages, stitched together, covered in a spiky script of runes. The ink still smells of paint. Some runes appear again and again.',
            'They guess letters; reveal a letter when they get it right. E and T start revealed.',
            ['“Look at the short words. Which three-letter word appears more than once?”', '“The word after ONLY is THE. What is the word before WHO?”', 'Reveal the letters for ALONE.'],
            'ONLY THE ONE WHO STANDS ALONE MAY LEARN THE CURSE THAT CANNOT BE BLOCKED.',
            'No failure. The answer tells them the painting must be visited alone.'),
    *puzzle('The Serpent in the Stars', 'The Astronomy Tower, after The Old Cup or at night.',
            'The night sky is impossibly clear. Silver numbers shimmer beside eight stars. Carved on the parapet: “Draw the serpent. Begin at its eye, the brightest star, and always move to the next brightest.”',
            'They call two stars to join; tap one, then the other.',
            ['“Which is the very brightest? That is the eye.”', '“Compare the sizes. Each line goes to the next biggest star.”', '“Start 5, 2, 7…”'],
            '5, 2, 7, 1, 8, 3, 6, 4.', 'No failure. Wrong lines can be tapped again to remove them.'),
    *puzzle('The Moving Staircases', 'The Grand Staircase, at Curfew, or as a shortcut to the Undercroft.',
            'The staircases have swung loose and hang at odd angles over the drop. Somewhere below, a door glows. If you can line them up, there is a path.',
            'They name a piece; tap it to turn it a quarter clockwise. The path glows when it connects.',
            ['“Start from the arrow and trace one step at a time.”', '“The path snakes: right, down twice, right, up, right, then down twice to the door.”', 'Read out the first three turns from the GM panel.'],
            'See the GM panel for exact turns. Any working route counts.', 'A wrong turn costs time. If Filch is about, spin Out after curfew.'),
    *puzzle('The Scrambled Portrait', 'Any portrait corridor. The portrait tells them a secret when whole.',
            'A portrait has been sliced into nine squares and shuffled in its frame. One square is missing. The pieces groan as they slide.',
            'They name a piece next to the gap; tap it to slide it in.',
            ['“Fix the top row first, then the left column.”', '“Leave the last two rows until the end; rotate them like a wheel.”', 'Make the next three moves for them.'],
            'Pieces 1 to 8 in order, gap last. The shortest solution is 16 slides.',
            'No failure. When it is whole, the portrait says: “He did not arrive on the train. He was brought.”'),
    *puzzle('The Rune Floor', 'The Trials Beneath, or the Undercroft approach.',
            'The floor is made of stone tiles, each carved with a rune. Above the far door, five runes are cut deep into the stone. The air smells of old blood.',
            'They say which tile the walker steps on; tap it. A wrong step flashes red and sends them back to the start.',
            ['“The five runes above the door are the only safe ones, in that order.”', '“You can only step up, left or right. Never diagonally, never back.”', '“Start on the bottom row, fourth tile.”'],
            'Bottom row 4th tile, then (row from the bottom, column): 2-4, 2-5, 3-5, 3-4, 3-3, 4-3, 4-2, 4-1, 5-1, 5-2, 6-2.',
            'A wrong step: the floor bites for d4 damage (adjust HP). The walker goes back to the start.'),
]
